'use strict';
const api=window.gozero,$=s=>document.querySelector(s);let state,currentView='overview',dirty=false,lastLog=0;
const thermal=['正常','偏热','严重','临界'];const fmt=(n,suffix='',digits=0)=>Number.isFinite(n)?n.toFixed(digits)+suffix:'—';const hash=n=>Number.isFinite(n)?(n/1e6).toFixed(3)+' MH/s':'—';
function text(s,t){const e=$(s);if(e&&e.textContent!==String(t))e.textContent=t;}
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4500);}
async function action(fn){try{await fn();}catch(e){toast(e.message);}}
function view(v){currentView=v;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));document.querySelectorAll('nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('main').scrollTop=0;}
function fields(selector,rows){const e=$(selector),key=JSON.stringify(rows);if(e.dataset.key===key)return;e.dataset.key=key;e.replaceChildren(...rows.map(([label,value])=>{const row=document.createElement('div');row.className='field';const a=document.createElement('label'),b=document.createElement('span');a.textContent=label;b.className='value';b.textContent=value;row.append(a,b);return row;}));}
function hydrate(){const c=state.config;for(const[id,key]of [['wallet','wallet'],['worker','worker'],['pool','pool'],['host','host'],['port','port'],['cpu-threads','cpuThreads'],['duration','seconds'],['interval','interval'],['theme-select','theme']])$('#'+id).value=c[key];$('#thermal-stop').checked=c.stopOnThermal;$('#preset').value=({ 'hk2.innovlab.cc':'innovlab-hk','eu2.innovlab.cc':'innovlab-eu','stratum-apac.suprnova.cc':'suprnova-apac'})[c.host]||'custom';dirty=false;}
function config(){return{...state.config,wallet:$('#wallet').value.trim(),worker:$('#worker').value.trim(),pool:$('#pool').value,host:$('#host').value.trim(),port:Number($('#port').value),cpuThreads:Number($('#cpu-threads').value),seconds:Number($('#duration').value),interval:Number($('#interval').value),theme:$('#theme-select').value,stopOnThermal:$('#thermal-stop').checked};}
async function save(){state.config=await api.save(config());dirty=false;hydrate();render();}
function logs(){const rows=state.logs||[];if(lastLog===(rows.at(-1)?.id||0))return;lastLog=rows.at(-1)?.id||0;const row=l=>{const e=document.createElement('div');e.className='mac-log-row';for(const[tag,t]of [['time',new Date(l.at).toLocaleTimeString('zh-CN',{hour12:false})],['label',l.type],['span',l.text]]){const c=document.createElement(tag);c.textContent=t;e.append(c);}return e;};$('#work-log').replaceChildren(...rows.slice(-12).map(row));$('#log-list').replaceChildren(...rows.map(row));$('#work-log').scrollTop=$('#work-log').scrollHeight;$('#log-list').scrollTop=$('#log-list').scrollHeight;}
function render(){if(!state?.config)return;document.body.classList.toggle('light',state.config.theme==='light');const h=state.hardware||{},m=state.miner||{},f=state.fee||{};const busy=state.starting||m.status!=='idle'||f.active||f.switching;
 text('#gpu-name',h.gpu||'Apple GPU');text('#gpu-load',fmt(h.gpuLoad,'%'));text('#memory-total',fmt(h.memoryBytes/1073741824,' GB'));text('#model',h.model||'—');text('#model-id',h.modelId||'—');text('#cpu-name',h.chip||'—');text('#cpu-total','CPU '+fmt(h.cpuLoad,'%',1));text('#hardware-time',h.at?new Date(h.at).toLocaleTimeString():'扫描中');
 fields('#gpu-fields',[['设备',h.gpu||'—'],['GPU 核心',fmt(h.gpuCores)],['API','Apple Metal'],['内存架构','统一内存'],['架构','arm64'],['设备利用率',fmt(h.gpuLoad,'%')],['核心温度','—'],['整机功耗','—']]);
 fields('#cpu-fields',[['物理核心',fmt(h.cpuCores)],['当前利用率',fmt(h.cpuLoad,'%',1)],['性能核',fmt(h.performanceCores)],['能效核',fmt(h.efficiencyCores)]]);
 fields('#memory-fields',[['容量',fmt(h.memoryBytes/1073741824,' GB')],['空闲',fmt(h.freeMemory/1073741824,' GB',1)],['系统',h.os?'Darwin '+h.os:'—'],['热状态',thermal[h.thermalState]||'—']]);
 const used=h.memoryBytes?100*(1-h.freeMemory/h.memoryBytes):0;$('#memory-meter').value=used;text('#memory-used',fmt(used,' % 系统占用',1));
 const bars=$('#core-bars');if(bars.children.length!==h.perCore?.length){bars.replaceChildren(...(h.perCore||[]).map((_,i)=>{const e=document.createElement('div');e.className='core';const meter=document.createElement('meter');meter.min=0;meter.max=100;const label=document.createElement('small');label.textContent='#'+i;e.append(meter,label);return e;}));}(h.perCore||[]).forEach((n,i)=>{bars.children[i].firstChild.value=n??0;bars.children[i].title='CPU '+i+'：'+fmt(n,'%',1);});
 const workStatus={waiting:'等待有效计算',paused:'矿池暂停，等待新任务',mining:'持续计算中',reconnecting:'断线重连中'}[m.workState]||'运行中';
 const status={idle:'待机',starting:'启动中',running:m.session?.benchmark?'离线测速中':workStatus,stopping:'停止中'}[m.status]||'初始化';
 text('#session-status',status);text('#overview-status',state.ready?'本机设备已连接 · '+status:'正在读取本机设备');text('#footer-state',state.ready?(h.chip+' · '+status):'正在读取本机设备');text('#footer-thermal','系统热状态：'+(thermal[h.thermalState]||'—'));text('#mining-device',h.gpu||'Apple GPU');
 const r=m.rate||{};text('#total-hash',hash(r.total));text('#gpu-hash',hash(r.gpu));text('#cpu-hash',hash(r.cpu));text('#rate-label',m.status==='idle'?'最后一次采样 / 待机':'真实本地算力 · 非矿池结算');
 text('#accepted',m.totals?.accepted||0);text('#rejected',m.totals?.rejected||0);text('#submitted',m.totals?.submitted||0);
 text('#fee-phase',f.active?(f.phase==='service'?'0.5% 服务时段 · '+Math.ceil(f.feeRemainingSeconds)+'s':'当前为用户收款时段'):'分时服务费 0.5% · 余额跨任务累计');
 text('#run-status',busy?(m.session?.benchmark?'离线自检／测速，不连接矿池':'本次最多 '+state.config.seconds+' 秒，到时自动停止'):'不会自动挖矿；关闭窗口会停止任务');
 for(const id of ['wallet','worker','pool','preset','host','port','cpu-threads','duration','interval','theme-select','thermal-stop','save-mining','save-settings','theme'])$('#'+id).disabled=busy;
 for(const id of ['start','benchmark','scan'])$('#'+id).disabled=busy||!state.ready;
 document.querySelectorAll('[data-stop]').forEach(e=>e.disabled=!busy);
 if(m.session?.benchmark){text('#benchmark-hash',m.status==='idle'?hash(r.total):'测速进行中…');text('#benchmark-status',m.status==='idle'?'本次结果已保存到本机报告目录':'正在执行算法自检、预热与30秒搜索');text('#benchmark-gpu',hash(r.gpu));text('#benchmark-cpu',hash(r.cpu));}
 const pts=m.points||[],max=Math.max(1,...pts.map(p=>p.total));$('#hash-line').setAttribute('d',pts.map((p,i)=>(i?'L':'M')+(i/Math.max(1,pts.length-1)*856+2).toFixed(1)+','+(67-p.total/max*62).toFixed(1)).join(' '));text('#chart-status',pts.length?'已采样 '+pts.length+' 点':'等待实际算力');logs();clock();
}
function clock(){const m=state?.miner;const s=m?.status!=='idle'&&m?.session?Math.max(0,Math.floor((Date.now()-m.session.startedAt)/1000)):0;text('#runtime',[Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(n=>String(n).padStart(2,'0')).join(':'));}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)view(b.dataset.view);if(b.dataset.window)action(()=>api.window(b.dataset.window));if(b.hasAttribute('data-stop'))action(()=>api.stop());if(b.dataset.open)action(()=>api.open(b.dataset.open));});
document.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',()=>dirty=true));
$('#preset').onchange=()=>{const p={'innovlab-hk':['innovlab','hk2.innovlab.cc',19601],'innovlab-eu':['innovlab','eu2.innovlab.cc',19601],'suprnova-apac':['suprnova','stratum-apac.suprnova.cc',3341]}[$('#preset').value];if(p){$('#pool').value=p[0];$('#host').value=p[1];$('#port').value=p[2];}dirty=true;};
$('#save-mining').onclick=()=>action(async()=>{await save();toast('挖矿配置已保存');});$('#save-settings').onclick=()=>action(async()=>{await save();toast('设置已保存');});
$('#start').onclick=()=>action(async()=>{await save();await api.start();});$('#benchmark').onclick=()=>action(async()=>{await save();await api.benchmark();});
$('#scan').onclick=()=>action(async()=>{state=await api.scan();render();});$('#theme').onclick=()=>action(async()=>{$('#theme-select').value=state.config.theme==='dark'?'light':'dark';await save();});$('#export-logs').onclick=()=>action(async()=>{if(await api.exportLogs())toast('日志已导出');});
api.subscribe(s=>{const initial=!state;state=s;if(initial)hydrate();render();});action(async()=>{state=await api.bootstrap();hydrate();render();});setInterval(clock,1000);
