'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {DualTasks,taskConfig}=require('../src/dual-tasks.cjs');
const {ConfigStore,validate}=require('../src/config.cjs');
const {FeeController}=require('../src/service-fee.cjs');
const {compactState}=require('../src/floating.cjs');
const id='a'.repeat(20),wallet='0x02'+'b'.repeat(62);
class FakeMiner{
 constructor(){this.status='idle';this.jobs=new Map();this.session=null;this.starts=[];this.installing=false}
 async installed(){return true}
 async start(c){this.starts.push(c);if(this.failure)throw Error(this.failure);this.status='running';this.session={coin:c.coin,startedAt:Date.now(),performance:c.performance};this.jobs.set(id,{id,status:'running',telemetry:{hash:c.coin==='ZCD'?8000:2500000000,at:Date.now()}});if(this.gate)await this.gate;return this.snapshot()}
 async stop(){this.status='idle';this.jobs.clear()}
 snapshot(){return{status:this.status,session:this.session,jobs:[...this.jobs.values()]}}
}
async function setup(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gozer-dual-')),store=new ConfigStore(dir),gpu=new FakeMiner(),cpu=new FakeMiner();await store.save({coin:'PRL',selected:[id],wallets:{PRL:'prl1testwalletonlyoffline',ZCD:wallet},workbenchMode:'dual',taskProfiles:{}});const gpuFee=new FeeController(gpu,dir,()=>{},()=>{});await gpuFee.load();const cpuFee=new FeeController(cpu,dir,()=>{},()=>{}),dual=new DualTasks({store,gpu,cpu,gpuFee,cpuFee,hardware:()=>({gpus:[{id}]}),ready:()=>true,changed:()=>{}});t.after(async()=>{await dual.stopAll();await fs.rm(dir,{force:true,recursive:true})});return{dir,store,gpu,cpu,gpuFee,cpuFee,dual}}
test('dual migration keeps GPU settings, gives CPU a separate balanced budget, and rejects cross-device coins',()=>{
 const c=validate({coin:'QTC',performance:100,worker:'old',selected:[id],taskProfiles:{}});assert.equal(taskConfig(c,'gpu').coin,'QTC');assert.equal(taskConfig(c,'gpu').performance,100);assert.equal(taskConfig(c,'cpu').coin,'ZCD');assert.equal(taskConfig(c,'cpu').performance,75);assert.deepEqual(taskConfig(c,'gpu').selected,[id]);assert.throws(()=>validate({taskProfiles:{gpu:{coin:'ZCD'}}}));assert.throws(()=>validate({taskProfiles:{cpu:{coin:'YSR'}}}));assert.throws(()=>validate({taskProfiles:{cpu:{command:'evil'}}}));assert.throws(()=>validate({taskProfiles:{cpu:{wallets:{ZCD:'01'+'a'.repeat(62)}}}}));
});
test('two miners run concurrently; stopping CPU leaves GPU and its fee scheduler running',async t=>{const x=await setup(t);const results=await x.dual.startAll();assert.ok(results.every(r=>r.ok));assert.equal(x.gpu.status,'running');assert.equal(x.cpu.status,'running');await x.dual.stop('cpu');assert.equal(x.cpu.status,'idle');assert.equal(x.cpuFee.active,false);assert.equal(x.gpu.status,'running');assert.equal(x.gpuFee.active,true);assert.equal(x.gpu.starts[0].coin,'PRL');assert.equal(x.cpu.starts[0].coin,'ZCD');await assert.rejects(x.dual.save('gpu',{performance:50}),/停止/);await x.dual.save('cpu',{cpuThreads:128,performance:100});assert.equal(x.dual.config('cpu').cpuThreads,128);assert.equal(x.dual.config('gpu').performance,75)});
test('one task launch failure and abnormal exit do not stop or restart the other task',async t=>{const x=await setup(t);x.cpu.failure='pool rejected';const r=await x.dual.startAll();assert.equal(r[1].ok,false);assert.equal(x.gpu.status,'running');assert.equal(x.cpuFee.active,false);x.cpu.failure=null;await x.dual.start('cpu');x.cpu.status='idle';x.cpuFee.tick();assert.equal(x.cpuFee.active,false);assert.equal(x.gpuFee.active,true);assert.equal(x.gpu.starts.length,1)});
test('concurrent configuration saves retain both profiles and default CPU uses logical threads',async t=>{const x=await setup(t);await Promise.all([x.dual.save('gpu',{performance:90,worker:'gpu'}),x.dual.save('cpu',{performance:100,cpuThreads:128,worker:'cpu'})]);const reload=new ConfigStore(x.dir);await reload.load();assert.equal(reload.value.taskProfiles.gpu.performance,90);assert.equal(reload.value.taskProfiles.cpu.cpuThreads,128);assert.equal(require('../src/mining-devices.cjs').cpuThreads(taskConfig(reload.value,'cpu'),{cpu:[{Name:'64C',NumberOfCores:64,NumberOfLogicalProcessors:128}]}),128);assert.equal(reload.value.taskProfiles.gpu.worker,'gpu')});
test('both 0.5% schedulers persist one ledger without losing legacy balances or double charging',async t=>{const x=await setup(t);const legacy=x.gpuFee.ledger.key('QTC','old');x.gpuFee.ledger.credit(legacy,199);await x.dual.startAll();clearInterval(x.gpuFee.timer);clearInterval(x.cpuFee.timer);for(const f of [x.gpuFee,x.cpuFee])for(let i=0;i<199;i++)f.account(f.last+1000);assert.ok(Math.abs(x.gpuFee.ledger.entry(x.gpuFee.key).balance-1)<1e-8);assert.ok(Math.abs(x.cpuFee.ledger.entry(x.cpuFee.key).balance-1)<1e-8);await Promise.all([x.gpuFee.persist(),x.cpuFee.persist()]);const recovered=new FeeController(x.gpu,x.dir,()=>{},()=>{});await recovered.load();assert.equal(Object.keys(recovered.ledger.entries).length,3);assert.equal(recovered.ledger.entry(legacy).balance,1);assert.ok(Math.abs(recovered.ledger.entry(x.cpuFee.key).balance-1)<1e-8);assert.equal(x.gpuFee.snapshot().rate,.005);assert.equal(x.cpuFee.snapshot().rate,.005)});
test('stop during pending start cancels only its task and cannot launch it again',async t=>{const x=await setup(t);let release;x.cpu.gate=new Promise(r=>release=r);const cpuStart=x.dual.start('cpu');await x.dual.start('gpu');await x.dual.stop('cpu');release();await assert.rejects(cpuStart,/取消/);assert.equal(x.cpu.status,'idle');assert.equal(x.gpu.status,'running');await x.dual.stopAll();assert.equal(x.gpu.status,'idle')});
test('floating monitor separates algorithm rates, clears stale samples, and keeps stop available for CPU only',async t=>{const x=await setup(t);await x.dual.startAll();const s={config:x.store.value,miner:x.gpu.snapshot(),serviceFee:x.gpuFee.snapshot(),dual:x.dual.snapshot()};let mini=compactState(s);assert.equal(mini.hash,null);assert.equal(mini.tasks[0].hash,2500000000);assert.equal(mini.tasks[1].hash,8000);assert.equal(mini.day,null);await x.dual.stop('gpu');x.cpu.jobs.get(id).telemetry.at-=60000;s.miner=x.gpu.snapshot();s.dual=x.dual.snapshot();mini=compactState(s);assert.equal(mini.canStop,true);assert.equal(mini.status,'running');assert.equal(mini.tasks[1].hash,null);assert.equal(mini.stopped,false)});
