const{test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {verify,compare}=require('../src/updates.cjs'),{makeRecord,Records}=require('../src/records.cjs'),{validateRecord,createStore}=require('../../lib/assistant.cjs'),{validate,DEFAULT}=require('../src/config.cjs'),{compactState}=require('../src/floating.cjs'),{Miner}=require('../src/miner.cjs');
function sample(){const now=Date.now(),id='a'.repeat(20);return makeRecord({id,duty:50,samples:Array.from({length:30},(_,i)=>({hash:100+i,at:now-60000+i*1500})),powers:[100,110]}, {startedAt:now-120000,coin:'QTC',performance:75,wallet:'must-not-leak'}, {gpus:[{id,name:'Test GPU',vendor:'NVIDIA',memoryMiB:8192,driver:'596.08',uuid:'sensitive',pci:'01:00.0'}]},'0.3.0')}
test('server retention removes expired records from disk, not only public responses',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gozer-retention-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const old={...sample(),at:Date.now()-91*86400000};await fs.writeFile(path.join(dir,'benchmarks.json'),JSON.stringify([old]));const s=createStore(dir);assert.equal((await s.summary()).groups.length,0);assert.deepEqual(JSON.parse(await fs.readFile(path.join(dir,'benchmarks.json'),'utf8')),[])});
test('performance defaults migrate, budgets and consent reject invalid values',()=>{assert.equal(validate({}).performance,75);assert.equal(validate({}).shareBenchmarks,false);for(const v of [0,49,101,75.5,NaN])assert.throws(()=>validate({...DEFAULT,performance:v}));assert.throws(()=>validate({...DEFAULT,shareBenchmarks:'yes'}))});

test('floating performance uses active task budget; idle uses saved budget and shared mode boundaries',()=>{
 const {describe}=require('../renderer/performance.js');
 for(const [n,label]of [[50,'节能'],[64,'节能'],[65,'均衡'],[89,'均衡'],[90,'高性能'],[100,'高性能']])assert.equal(describe(n).label,label);
 const s={config:{performance:50},miner:{status:'running',session:{performance:90}}};
 let r=compactState(s);assert.equal(r.performanceLabel,'高性能 · 90%');assert.equal(r.performanceActive,true);
 s.miner.status='idle';r=compactState(s);assert.equal(r.performanceLabel,'节能 · 50%');assert.equal(r.performanceActive,false);
 s.config.performance=undefined;assert.equal(compactState(s).performanceLabel,'均衡 · 75%');
});
test('load feedback decreases owned process submission time and changing profile clears old samples',()=>{const m=new Miner(os.tmpdir(),()=>{},()=>{}),writes=[];m.session={performance:100,temperature:82};m.status='running';m.jobs.set('a',{id:'a',status:'running',duty:90,child:{stdin:{write:s=>writes.push(s)}},powers:[],samples:[{hash:123}]});m.checkHardware({gpus:[{id:'a',sensors:{at:Date.now(),load:100,temp:50,power:100}}]});assert.equal(writes[0],'duty:85\n');m.setPerformance(50);assert.equal(writes.at(-1),'duty:45\n');assert.equal(m.jobs.get('a').samples.length,0)});
test('records retain physical measurements without wallets, PCI, UUID or serial numbers',()=>{const r=sample();assert.equal(r.hash,114.5);assert.equal(r.watts,105);assert.equal(r.seconds,43.5);assert.deepEqual(validateRecord(r),r);assert.ok(!/wallet|uuid|pci|sensitive|must-not-leak/.test(JSON.stringify(r)));for(const extra of [{wallet:'leak'},{hash:Infinity},{seconds:1},{model:'<script>'}])assert.throws(()=>validateRecord({...r,...extra}))});
test('upload is opt-in, disabling stops further queued requests, successful records are idempotent',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gozer-records-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));let requests=0;const r=new Records(dir,async()=>{requests++;r.enabled=false;return Buffer.from('{"accepted":true}')},()=>{});r.rows=[{record:sample(),uploaded:false},{record:sample(),uploaded:false}];await r.flush();assert.equal(requests,0);r.enabled=true;await r.flush();assert.equal(requests,1);assert.equal(r.snapshot().uploaded,1);const next=new Records(dir,()=>{},()=>{});await next.load();assert.equal(next.snapshot().count,2)});
test('server deduplicates IDs and returns aggregate-only unverified data',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gozer-intake-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const s=createStore(dir),r=sample();await Promise.all([s.accept(r,'a'),s.accept(r,'a')]);const result=await s.summary();assert.equal(result.groups[0].samples,1);assert.equal(result.groups[0].hashMedian,r.hash);assert.equal(result.verification,'unverified-community');assert.ok(!JSON.stringify(result).includes(r.id));await assert.rejects(s.accept({...r,token:'not allowed'},'a'))});
test('update manifests require trusted signature, bounded URL, expiry and nondecreasing sequence',()=>{const k=crypto.generateKeyPairSync('ed25519'),data={schema:1,version:'0.4.0',sequence:2,publishedAt:Date.now(),expiresAt:Date.now()+100000,coins:['PRL','QTC'],notes:['test'],url:'https://pro.gozero.trade/downloads/gozer/GozerAssistant-0.4.0-win-x64.zip',sha256:'a'.repeat(64),bytes:123};const sign=d=>{const b=Buffer.from(JSON.stringify(d));return{payload:b.toString('base64'),signature:crypto.sign(null,b,k.privateKey).toString('base64')}};assert.equal(verify(sign(data),k.publicKey,1).version,'0.4.0');assert.throws(()=>verify({...sign(data),payload:Buffer.from('{}').toString('base64')},k.publicKey));assert.throws(()=>verify(sign(data),k.publicKey,3));assert.throws(()=>verify(sign({...data,expiresAt:1}),k.publicKey));assert.throws(()=>verify(sign({...data,url:'https://attacker.test/a.zip'}),k.publicKey));assert.equal(compare('0.10.0','0.3.0'),1)});
test('floating income periods keep zero, unknown and stale telemetry honest',()=>{let s={config:{coin:'QTC'},miner:{status:'running',jobs:[{status:'running',telemetry:{hash:100,at:Date.now()}}]},income:{coins:[{coin:'QTC',net:0}]},network:[{coin:'QTC',price:5,networkHash:1000}]};let r=compactState(s);assert.equal(r.hash,100);assert.equal(r.week,0);assert.equal(r.month,0);assert.equal(r.coin,'QTC');s.miner.jobs[0].telemetry.at-=30000;s.income.coins[0].net=null;r=compactState(s);assert.equal(r.hash,null);assert.equal(r.week,null)});
