const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');const{spawn}=require('node:child_process');
const GUARD=path.resolve(__dirname,'../vendor/ProcessGuard.exe');
async function until(fn,ms=5000){const end=Date.now()+ms;while(Date.now()<end){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,80))}throw Error('Timed out')}
const alive=pid=>{try{process.kill(pid,0);return true}catch{return false}};
test('captured console preserves stdout/stderr, isolates CUDA UUID, and still kills the owned child',async()=>{
 if(process.platform!=='win32')return;
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gozero-中文 capture-')),capturePath=path.join(dir,'output.log');let guard,pid;
 const uuid='GPU-12345678-1234-1234-1234-123456789abc',original=process.env.CUDA_VISIBLE_DEVICES;
 try{guard=spawn(GUARD,[String(process.pid)],{windowsHide:true,stdio:['pipe','pipe','pipe']});let errors='';guard.stderr.on('data',d=>errors+=d);guard.stdout.on('data',d=>{for(const line of String(d).split('\n'))try{pid=JSON.parse(line).pid||pid}catch{}});
 guard.stdin.write(JSON.stringify({exe:process.execPath,cwd:dir,capturePath,cudaUuid:uuid,duty:90,args:['-e',"console.log('output '+process.env.CUDA_VISIBLE_DEVICES+' '+process.env.CUDA_DEVICE_ORDER);console.error('error 中文');setInterval(()=>{},1000)"]})+'\n');
 const output=await until(async()=>{try{const s=await fs.readFile(capturePath,'utf8');return s.includes('error 中文')?s:false}catch{return false}});
 assert.match(output,new RegExp(uuid+' PCI_BUS_ID'));assert.equal(process.env.CUDA_VISIBLE_DEVICES,original);assert.equal(errors,'');await until(()=>pid);guard.stdin.end('stop\n');await until(()=>!alive(pid));
 }finally{guard?.kill();await new Promise(r=>setTimeout(r,100));await fs.rm(dir,{recursive:true,force:true})}
});
test('live duty changes really pause the owned process and explicit stop still releases it',async()=>{if(process.platform!=='win32')return;const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gozer-duty-')),file=path.join(dir,'ticks.txt');let guard;try{guard=spawn(GUARD,[String(process.pid)],{windowsHide:true,stdio:['pipe','pipe','pipe']});let pid,ack=0;guard.stdout.on('data',d=>{for(const line of String(d).split('\n'))try{const v=JSON.parse(line);if(v.pid)pid=v.pid;if(v.duty)ack=v.duty}catch{}});guard.stdin.write(JSON.stringify({exe:process.execPath,cwd:dir,duty:90,args:['-e',"const fs=require('fs');setInterval(()=>fs.appendFileSync(process.argv[1],'x'),20)",file]})+'\n');const size=async()=>{try{return(await fs.stat(file)).size}catch{return 0}};await until(async()=>await size()>5);const wait=ms=>new Promise(r=>setTimeout(r,ms));guard.stdin.write('duty:5\n');await until(()=>ack===5);await wait(550);let before=await size();await wait(1600);const low=await size()-before;guard.stdin.write('duty:90\n');await until(()=>ack===90);await wait(550);before=await size();await wait(1600);const high=await size()-before;assert.ok(high>low*2,{low,high});guard.stdin.end('stop\n');await until(()=>!alive(pid))}finally{guard?.kill();await new Promise(r=>setTimeout(r,100));await fs.rm(dir,{recursive:true,force:true})}});
test('native job kills both child and grandchild on stop and guard crash; argument quoting survives',async()=>{if(process.platform!=='win32')return;const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gozer-guard-test-'));try{for(const mode of['stop','crash']){const out=path.join(dir,mode+'.json'),quoted='中文路径 参数 space and "quotes" \\ ending\\';const script="const fs=require('fs'),cp=require('child_process');const c=cp.spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{windowsHide:true});fs.writeFileSync(process.argv[1],JSON.stringify({pid:process.pid,child:c.pid,arg:process.argv[2]}));setInterval(()=>{},1000)";const guard=spawn(GUARD,[String(process.pid)],{windowsHide:true,stdio:['pipe','pipe','pipe']});let errors='';guard.stderr.on('data',d=>errors+=d);guard.stdin.write(JSON.stringify({exe:process.execPath,args:['-e',script,out,quoted],cwd:dir})+'\n');const result=await until(async()=>{try{return JSON.parse(await fs.readFile(out,'utf8'))}catch{return false}});assert.equal(result.arg,quoted);assert.ok(alive(result.pid));assert.ok(alive(result.child));if(mode==='stop')guard.stdin.end('stop\n');else guard.kill();await until(()=>!alive(result.pid)&&!alive(result.child));assert.equal(errors,'')}}finally{await fs.rm(dir,{recursive:true,force:true})}});
test('parent death is detected even if guard stdin remains referenced',async()=>{if(process.platform!=='win32')return;const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gozer-parent-test-'));try{const out=path.join(dir,'child.json'),parentScript=path.join(dir,'parent.cjs');await fs.writeFile(parentScript,`const{spawn}=require('node:child_process');const guard=spawn(${JSON.stringify(GUARD)},[String(process.pid)],{windowsHide:true,stdio:['pipe','ignore','ignore']});guard.stdin.write(JSON.stringify({exe:process.execPath,cwd:${JSON.stringify(dir)},args:['-e',${JSON.stringify("require('fs').writeFileSync(process.argv[1],JSON.stringify({pid:process.pid}));setInterval(()=>{},1000)")},${JSON.stringify(out)}]})+'\\n');setInterval(()=>{},1000);`);const parent=spawn(process.execPath,[parentScript],{windowsHide:true,stdio:'ignore'});const result=await until(async()=>{try{return JSON.parse(await fs.readFile(out,'utf8'))}catch{return false}});parent.kill();await until(()=>!alive(result.pid))}finally{await fs.rm(dir,{recursive:true,force:true})}});
