const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {installKernel}=require('../src/kernel-install.cjs'),{readBody}=require('../src/download-body.cjs');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
async function setup(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gozer-install-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const body=Buffer.from('isolated archive fixture'),exe=path.join(dir,'fixture.exe'),binary=Buffer.from('not executable, never launched'),updates=[],logs=[];return{dir,exe,metadata:{version:'test',url:'https://fixture.invalid',sha256:hash(body),exeSha256:hash(binary)},updates,logs,update:p=>updates.push(p),log:(type,text)=>logs.push({type,text}),request:async(url,opts)=>{opts.onProgress({received:0,total:body.length});opts.onProgress({received:body.length,total:body.length});return body},extractArchive:async()=>fs.writeFile(exe,binary)}}
test('installation exposes ordered real stages, checks both hashes and cleans temporary archive',async t=>{const o=await setup(t);assert.equal(await installKernel(o),true);assert.deepEqual(o.updates.map(x=>x.stage),['connecting','downloading','downloading','verifying','extracting','checking','ready']);assert.equal(o.updates.at(-1).version,'test');assert.ok(o.logs.some(x=>x.text.includes('100%')));await assert.rejects(fs.access(path.join(o.dir,'download.zip')))});
test('corrupt download cannot extract; failure remains visible and retry succeeds',async t=>{const o=await setup(t),good=o.metadata.sha256;let extracted=false;const extract=o.extractArchive;o.extractArchive=async(...args)=>{extracted=true;return extract(...args)};o.metadata.sha256='0'.repeat(64);await assert.rejects(installKernel(o),/SHA256/);assert.equal(extracted,false);assert.equal(o.updates.at(-1).stage,'error');o.metadata.sha256=good;await installKernel(o);assert.equal(o.updates.at(-1).stage,'ready')});
test('extraction, executable hash and network failures never report ready',async t=>{for(const failure of ['extract','binary','network']){const o=await setup(t);if(failure==='extract')o.extractArchive=async()=>{throw Error('fixture extraction failed')};if(failure==='binary')o.metadata.exeSha256='0'.repeat(64);if(failure==='network')o.request=async()=>{throw Error('offline')};await assert.rejects(installKernel(o));assert.equal(o.updates.at(-1).stage,'error');assert.ok(!o.updates.some(x=>x.stage==='ready'));await assert.rejects(fs.access(path.join(o.dir,'download.zip')))}});
test('stream progress uses byte counts, supports unknown lengths, and rejects truncated or oversized responses',async()=>{
 for(const headers of [{'content-length':'4'},{}]){const events=[];const result=await readBody(new Response('abcd',{headers}),5,p=>events.push(p));assert.equal(result.toString(),'abcd');assert.equal(events[0].received,0);assert.equal(events.at(-1).received,4);assert.equal(events.at(-1).total,headers['content-length']?4:null)}
 await assert.rejects(readBody(new Response('abcd',{headers:{'content-length':'6'}}),5),/过大/);
 await assert.rejects(readBody(new Response('abcdef'),5),/超过/);
 await assert.rejects(readBody(new Response('abc',{headers:{'content-length':'4'}}),5),/不完整/);
});
