const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
async function run(win,getState,floating,trayMenu){const dir=path.resolve(__dirname,'../artifacts');await fs.mkdir(dir,{recursive:true});const js=code=>win.webContents.executeJavaScript(code,true).catch(e=>{throw Error(e.message+' · '+code.slice(0,180))});const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function until(code,timeout=20000){const end=Date.now()+timeout;while(Date.now()<end){if(await js(code))return;await sleep(150)}throw Error('UI wait failed: '+code)}const shot=async name=>{await sleep(120);await fs.writeFile(path.join(dir,name+'.png'),(await win.webContents.capturePage()).toPNG())};await until("document.querySelector('#footer-state').textContent==='系统就绪'");
 const errors=[];win.webContents.on('console-message',(_e,level,message)=>{if(level===3)errors.push(message)});
 const dims=await js('({width:innerWidth,height:innerHeight})');assert.ok(Math.abs(dims.width-720)<=2&&Math.abs(dims.height-540)<=2,'720x540 within Windows fractional-DPI rounding');const s=getState();assert.ok(s.hardware.gpus.some(g=>g.sensors));assert.ok(s.hardware.memory.length);const gpuId=s.hardware.gpus.find(g=>g.vendor==='NVIDIA').id;
 assert.deepEqual(s.config.selected,[gpuId],'startup reconciles the seeded duplicate selection');
 const legacyId=require('../src/device-selection.cjs').deviceId(s.hardware.gpus.find(g=>g.id===gpuId).sensors.uuid);
 await js(`(async()=>{const s=await gozer.bootstrap();await gozer.save({...s.config,selected:[${JSON.stringify(legacyId)},${JSON.stringify(gpuId)}]});await gozer.scan()})()`);
 assert.deepEqual(getState().config.selected,[gpuId],'old UUID and current PnP collapse to one physical GPU');
 await js(`(async()=>{const s=await gozer.bootstrap();await gozer.save({...s.config,selected:[${JSON.stringify(gpuId)},'ffffffffffffffffffff']})})()`);
 await until("!document.querySelector('#clear-missing').hidden");
 assert.equal(await js("document.querySelector('#start').disabled"),true);
 await js("document.querySelector('#clear-missing').click()");await until("document.querySelector('#clear-missing').hidden");
 assert.deepEqual(getState().config.selected,[gpuId]);
 await js(`(async()=>{const state=await gozer.bootstrap();await gozer.save({...state.config,selected:[${JSON.stringify(gpuId)}],coin:'PRL'});document.querySelector('[data-id="${gpuId}"] .gpu-name').click()})()`);await sleep(300);await shot('overview-live');
 const before=await js("window.probe={nodes:[...document.querySelectorAll('.gpu-row,.field')],positions:[...document.querySelectorAll('.gpu-row,.field')].map(n=>JSON.stringify(n.getBoundingClientRect().toJSON()))};true");await sleep(5000);const changes=await js('probe.nodes.map((n,i)=>({connected:n.isConnected,before:probe.positions[i],after:JSON.stringify(n.getBoundingClientRect().toJSON()),name:n.outerHTML.slice(0,160)})).filter(x=>!x.connected||x.before!==x.after)');await fs.writeFile(path.join(dir,'stability-diff.json'),JSON.stringify(changes,null,2));assert.deepEqual(changes,[]);
 await js("document.querySelector('[data-detail=cpu]').click()");assert.match(await js("document.querySelector('#details-body').textContent"),/逻辑处理器/);await js("document.querySelector('#details-close').click();document.querySelector('nav [data-view=mining]').click()");assert.equal(await js("document.querySelector('#coin-tabs [data-coin=TSC]')"),null);assert.deepEqual(await js("[...document.querySelectorAll('#estimate-coin option')].map(n=>n.value)"),['PRL','QTC']);assert.equal(getState().config.coin,'PRL');assert.equal(getState().config.wallets.TSC,'tc1qfixturepreserved');await sleep(250);await shot('mining-live');
 await js("document.querySelector('nav [data-view=earnings]').click();document.querySelector('#income-refresh').click()");await until("!document.querySelector('#income-refresh').disabled",45000);await shot('earnings-live');assert.match(await js("document.querySelector('#income-rows').textContent"),/Laptop/);
 assert.equal(await js("document.querySelectorAll('#network-strip .network-card').length"),2);assert.ok(getState().network.some(n=>n.fetchedAt&&!n.error),'at least one real network API must succeed');
 await js("document.querySelector('#estimate-coin').value='PRL';document.querySelector('#estimate-coin').dispatchEvent(new Event('change'));document.querySelector('#manual-hash').value='100';document.querySelector('#manual-unit').value='1000000000000';document.querySelector('#manual-power').value='100';document.querySelector('#save-manual').click()");
 await until("state.config.manualInputs.PRL[document.querySelector('#manual-device').value]?.hash===100e12");
 assert.equal(getState().income.coins[0].rows[0].manual,true);await shot('earnings-manual');
 assert.equal(await js("document.querySelector('#fee-details').closest('footer')!==null && !document.querySelector('#mining .fee-disclosure') && !document.querySelector('#mining .fee-current')"),true);
 await js("document.querySelector('nav [data-view=mining]').click();document.querySelector('#fee-details').click()");
 assert.deepEqual(await js("[...document.querySelectorAll('.fee-address')].map(n=>n.value)"),['PRL','QTC'].map(c=>require('../src/service-fee.cjs').ADDRESSES[c]));await shot('fee-disclosure');
 await js("document.querySelector('#details-close').click();document.querySelector('nav [data-view=information]').click()");await sleep(300);await shot('information-live');
 await js("document.querySelector('[data-info-filter=price]').click()");assert.equal(await js("document.querySelector('[data-info-filter=price]').classList.contains('active')"),true);
 await js("gozer.window('close')");await sleep(1000);assert.equal(win.isDestroyed(),false);assert.equal(floating.wantVisible,true);const mini=floating.win;await sleep(500);assert.match(await mini.webContents.executeJavaScript('document.body.textContent'),/GPU/);assert.equal(await mini.webContents.executeJavaScript('typeof require'),'undefined');

 assert.equal(await mini.webContents.executeJavaScript("document.querySelector('header>b').textContent"),'Gozero助手');
 assert.ok(await mini.webContents.executeJavaScript("parseFloat(getComputedStyle(document.querySelector('.monitor-card')).borderRadius)>=14"));
 assert.ok(await mini.webContents.executeJavaScript("parseFloat(getComputedStyle(document.querySelector('#hash')).fontSize)>parseFloat(getComputedStyle(document.querySelector('#price')).fontSize)*2"));
 const modes=await mini.webContents.executeJavaScript(`(()=>{const positions=[];const result=[];for(const percent of [50,75,100]){render({performance:percent,performanceActive:true,status:'running'});const el=document.querySelector('#budget');result.push(el.textContent);positions.push(JSON.stringify(el.getBoundingClientRect().toJSON()));if(el.scrollWidth>el.clientWidth)throw Error('performance label clipped');}if(new Set(positions).size!==1)throw Error('performance badge changes size');return result})()`);
 assert.deepEqual(modes,['节能 · 50%','均衡 · 75%','高性能 · 100%']);
 await mini.webContents.executeJavaScript(`render(${JSON.stringify(require('../src/floating.cjs').compactState(getState()))})`);
 const roundedCapture=await mini.webContents.capturePage();assert.equal(roundedCapture.toBitmap()[3],0,'floating corner must be transparent');
 await mini.webContents.executeJavaScript(`render({...${JSON.stringify(require('../src/floating.cjs').compactState(getState()))},hash:123e9,hashAverage:{minutes:5,complete:true,running:true,fresh:true,retained:false,coverage:.97},status:'running'})`);
 await sleep(120);await fs.writeFile(path.join(dir,'floating-hash-fixture-dark.png'),(await mini.webContents.capturePage()).toPNG());
 await mini.webContents.executeJavaScript("document.body.classList.add('light')");await sleep(120);await fs.writeFile(path.join(dir,'floating-hash-fixture-light.png'),(await mini.webContents.capturePage()).toPNG());floating.send(require('../src/floating.cjs').compactState(getState()));await sleep(120);
 await fs.writeFile(path.join(dir,'floating-live.png'),(await mini.webContents.capturePage()).toPNG());
 assert.ok(Math.abs(await mini.webContents.executeJavaScript('parseFloat(getComputedStyle(document.body).fontSize)')-9.72)<.05);
 await mini.webContents.executeJavaScript("mini.hide()");assert.equal(floating.wantVisible,false);assert.equal(win.isVisible(),false);await sleep(500);assert.equal(floating.wantVisible,false,'sensor updates must not reopen hidden card');
 assert.ok(trayMenu.items.some(i=>i.label==='退出'));trayMenu.items.find(i=>i.label==='复原主窗口').click();assert.equal(win.isVisible(),true);
 await js("gozer.window('close')");await sleep(200);mini.close();assert.equal(floating.wantVisible,false);assert.equal(win.isVisible(),false);trayMenu.items.find(i=>i.label==='复原主窗口').click();assert.equal(win.isVisible(),true);

 const overflow=await js("[...document.querySelectorAll('.view')].map(n=>({id:n.id,scroll:n.scrollWidth,width:n.clientWidth})).filter(n=>n.width&&n.scroll>n.width+2)");assert.deepEqual(overflow,[]);
 await js("document.querySelector('nav [data-view=overview]').click();document.querySelector('#theme').click()");await until("document.body.classList.contains('light')");await shot('overview-light');await js("document.querySelector('#theme').click()");await sleep(200);
 await js("document.querySelector('nav [data-view=mining]').click();document.querySelector('#performance').value='50';document.querySelector('#performance-apply').click()");await until("state.config.performance===50");await js("document.querySelector('nav [data-view=settings]').click()");await shot('settings-services');const core=await js("gozer.nativeCheck()");assert.equal(core.passed,true);assert.ok(core.referenceChecks>=16);const release=await js("gozer.checkUpdate()");assert.equal(release.error,null);assert.ok(/^\d+\.\d+\.\d+$/.test(release.release.version));assert.ok(release.release.sequence>=1);await shot('settings-services');
 // Isolated renderer fixtures only: never call start or attach a wallet/pool.
 await js("document.querySelector('nav [data-view=mining]').click()");
 const ui=await js(`(()=>{const original=state;try{state=structuredClone(state);state.config.selected=[state.hardware.gpus.find(g=>g.vendor==='NVIDIA').id];const g=state.hardware.gpus.find(g=>g.id===state.config.selected[0]);state.config.temperature=82;g.sensors={...g.sensors,at:Date.now(),temp:85};state.miner={status:'running',session:{startedAt:Date.now()-60000},jobs:[{id:g.id,status:'running',telemetry:{hash:1e12,at:Date.now()-59000}}]};renderHardware();for(let i=0;i<12;i++){state.miner.jobs[0].telemetry={hash:(1+i%4*.12)*1e12,at:Date.now()-55000+i*5000};hashHistory.update(state.miner,state.miner.jobs[0].telemetry.at)}renderMining();const positions=[...document.querySelectorAll('#mining .panel,#mining .mining-stats')].map(n=>JSON.stringify(n.getBoundingClientRect().toJSON()));const result={nav:document.querySelector('nav button:last-child').dataset.view,consent:!!document.querySelector('#fee-consent'),curve:document.querySelector('#hash-line').getAttribute('d'),hot:document.querySelector('#worker-rows .hot')?.textContent,gpuHot:!!document.querySelector('#gpu-list .hot'),detailHot:!!document.querySelector('#gpu-fields .hot'),animation:getComputedStyle(document.querySelector('.mining-motion i')).animationName,chartHeight:document.querySelector('#hash-chart').getBoundingClientRect().height,cta:document.querySelector('#benchmark').getBoundingClientRect().height};state.miner.jobs[0].telemetry={at:Date.now()+1,hash:2e12};renderMining();result.stable=JSON.stringify(positions)===JSON.stringify([...document.querySelectorAll('#mining .panel,#mining .mining-stats')].map(n=>JSON.stringify(n.getBoundingClientRect().toJSON())));document.querySelector('.mining-workspace').scrollTop=9999;return result}finally{state=original}})()`);
 assert.equal(ui.nav,'information');assert.equal(ui.consent,false);assert.match(ui.curve,/ L/);assert.equal(ui.hot,'85°C');assert.ok(ui.gpuHot&&ui.detailHot&&ui.stable);assert.equal(ui.animation,'mine-pulse');assert.ok(ui.chartHeight>=50);
 await shot('mining-curve-fixture');await js('render()');
 await js("document.querySelector('nav [data-view=earnings]').click()");assert.ok(await js("document.querySelector('#benchmark').getBoundingClientRect().height>=26"));
 await js("document.querySelector('nav [data-view=mining]').click();document.querySelector('.mining-workspace').scrollTop=0;document.querySelector('#toast').hidden=true");
 const installUi=await js(`(()=>{window.installFixtureOriginal=state;state=structuredClone(state);state.miner.installing=true;state.miner.installation={stage:'downloading',received:41*1048576,total:82*1048576,version:'1.5.4'};state.logs.push({at:Date.now(),type:'安装',text:'测试界面：连接官方源'},{at:Date.now(),type:'安装',text:'测试界面：下载 41.0 / 82.0 MB · 50%'});render();const box=()=>JSON.stringify(document.querySelector('#kernel-install').getBoundingClientRect().toJSON());const before=box(),half=document.querySelector('#install-progress').value;state.miner.installation.received=60*1048576;renderInstallation();return{half,stable:before===box(),visible:!document.querySelector('#kernel-install').hidden,bodyFont:parseFloat(getComputedStyle(document.body).fontSize),navFont:parseFloat(getComputedStyle(document.querySelector('nav button')).fontSize)}})()`);
 assert.equal(installUi.half,50);assert.ok(installUi.stable&&installUi.visible);assert.ok(Math.abs(installUi.bodyFont-10.8)<.05&&Math.abs(installUi.navFont-10.8)<.05);await shot('install-progress-fixture');
 assert.equal(await js("state.miner.installation.stage='extracting';renderInstallation();document.querySelector('#install-progress').hasAttribute('value')"),false);
 assert.match(await js("state.miner.installing=false;state.kernel.installed=true;state.miner.installation.stage='ready';render();document.querySelector('#kernel-state').textContent"),/1.5.4.*可用/);await shot('install-ready-fixture');await js('state=window.installFixtureOriginal;delete window.installFixtureOriginal;render()');


 // Read-only live pool account lookup; isolated profile, never start miners.
 const lookupConfig=getState().config;
 await js(`(async()=>{const s=await gozer.bootstrap();await gozer.save({...s.config,coin:'QTC',wallets:{...s.config.wallets,QTC:${JSON.stringify(require('../src/service-fee.cjs').ADDRESSES.QTC)}}})})()`);
 await until("state.poolAccount?.supported && !!state.poolAccount.sections.balance?.value && !!state.poolAccount.sections.payouts?.value",25000);
 assert.equal(getState().poolAccount.source,'Kryptex');assert.ok(getState().poolAccount.sections.balance.value.confirmed>=0);
 await js("document.querySelector('nav [data-view=mining]').click();document.querySelector('.mining-workspace').scrollTop=9999");await shot('pool-account-live');
 await js("document.querySelector('#mining .account-payouts').click()");assert.equal(await js("document.querySelector('#payout-dialog').open"),true);await shot('pool-payouts-live');
 await js(`document.querySelector('#payout-close').click();gozer.save(${JSON.stringify(lookupConfig)})`);await until("state.config.coin==='PRL'&&!state.poolAccount.supported");await js('configInputs();render()');
 assert.equal(await js("state.config.temperature"),90);assert.equal(await js("document.querySelector('header>b').textContent"),'Gozero助手');
 // Configure regional endpoints without contacting a wallet or starting miners.
 await js("document.querySelector('nav [data-view=mining]').click()");
 assert.match(await js("document.querySelector('#pool').value"),/prl-sg/);
 await js("document.querySelector('#pool-preset').value=state.poolOptions[1].url;document.querySelector('#pool-preset').dispatchEvent(new Event('change'));document.querySelector('#hash-window').value='10';document.querySelector('#pool-backups-open').click()");
 assert.equal(await js("document.querySelector('#pool-dialog').open"),true);await shot('pool-backups');
 await js("document.querySelector('#pool-backups-save').click()");await until("state.config.hashWindowMinutes===10&&state.config.pools.PRL.includes('prl-hk')");
 assert.match(await js("state.config.poolBackups.PRL[0]"),/prl-sg/);assert.equal(await js("document.querySelector('#pool-dialog').open"),false);
 await js("document.querySelector('#pool-preset').value=state.poolOptions[0].url;document.querySelector('#pool-preset').dispatchEvent(new Event('change'));document.querySelector('#hash-window').value='5';document.querySelector('#save-mining').click()");await until("state.config.hashWindowMinutes===5&&state.config.pools.PRL.includes('prl-sg')");
 // A completed average survives instantaneous gaps and shows stale/stop status.
 const avgUi=await js(`(()=>{const original=state;try{state=structuredClone(state);const at=Date.now();state.miner.session={coin:state.config.coin,selected:state.config.selected,startedAt:at-320000};state.miner.status='running';state.miner.hashAverage={hash:123e9,minutes:5,coverage:.96,complete:true,running:true,fresh:true,retained:false,from:at-320000,to:at-20000,remainingMs:280000};renderMining();const first=document.querySelector('#total-hash').textContent;state.miner.jobs=[];state.miner.hashAverage.fresh=false;renderMining();const stable=first===document.querySelector('#total-hash').textContent,note=document.querySelector('#hash-average-note').textContent;state.miner.hashAverage.running=false;renderMining();return{first,stable,note,stopped:document.querySelector('#hash-average-note').textContent}}finally{state=original;render()}})()`);
 assert.match(avgUi.first,/123.*GH/);assert.ok(avgUi.stable);assert.match(avgUi.note,/中断/);assert.match(avgUi.stopped,/已停止/);

 // Workbench actions, persisted kernel selection, and a bottom log that fills spare height.
 await js("document.querySelector('nav [data-view=mining]').click();document.querySelector('#kernel-select').value='krig-1.5.4';document.querySelector('#save-mining').click()");await until("state.config.kernels.PRL==='krig-1.5.4'");
 await js("document.querySelector('#coin-tabs [data-coin=QTC]').click()");await until("state.config.coin==='QTC'");assert.equal(await js("document.querySelector('#kernel-select').value"),'auto');assert.equal(await js("document.querySelector('#kernel-select option[value=gozer-qtc-experimental]').disabled"),true);
 await js("document.querySelector('#coin-tabs [data-coin=PRL]').click()");await until("state.config.coin==='PRL'");assert.equal(await js("document.querySelector('#kernel-select').value"),'krig-1.5.4');
 const geometry=await js(`(()=>{const log=document.querySelector('.workbench-log').getBoundingClientRect(),main=document.querySelector('main').getBoundingClientRect();return{buttons:[...document.querySelectorAll('#start,#stop,#save-mining')].map(n=>n.getBoundingClientRect().height),wallet:parseFloat(getComputedStyle(document.querySelector('#wallet')).fontSize),pool:parseFloat(getComputedStyle(document.querySelector('#pool')).fontSize),logHeight:log.height,bottom:main.bottom-log.bottom,overflow:document.querySelector('#mining').scrollWidth>document.querySelector('#mining').clientWidth+1}})()`);
 assert.ok(geometry.buttons.every(h=>h>=33));assert.ok(geometry.wallet>=11&&geometry.pool>=11);assert.ok(geometry.logHeight>=125&&geometry.bottom<=5&&!geometry.overflow);
 await js(`window.logsFixtureOriginal=state;state=structuredClone(state);state.logs=Array.from({length:150},(_,i)=>({id:10000+i,at:Date.now()+i,type:'矿工',text:'隔离界面测试日志 '+i+' · 不代表实际挖矿'}));document.querySelector('#workbench-follow').checked=true;renderWorkbenchLogs();document.querySelector('#toast').hidden=true`);
 assert.equal(await js("document.querySelectorAll('.workbench-log-row').length"),120);await shot('workbench-compact');
 const stableLog=await js(`(()=>{const el=document.querySelector('#workbench-log-list');document.querySelector('#workbench-follow').checked=false;el.scrollTop=300;const anchor=el.children[25],before=anchor.getBoundingClientRect().top;state.logs.push({id:20000,at:Date.now(),type:'矿工',text:'隔离测试新增日志'});renderWorkbenchLogs();return anchor.isConnected&&Math.abs(anchor.getBoundingClientRect().top-before)<1})()`);assert.equal(stableLog,true);
 win.setContentSize(720,960);await sleep(150);assert.ok(await js("document.querySelector('.workbench-log').getBoundingClientRect().height>126"));await shot('workbench-expanded');win.setContentSize(720,540);await sleep(150);
 await js('state=window.logsFixtureOriginal;delete window.logsFixtureOriginal;render()');
 const denied=await js("(async()=>{try{await gozer.open('file:///C:/Windows/System32/calc.exe');return false}catch{return true}})()");assert.ok(denied);assert.equal(getState().miner.status,'idle');assert.deepEqual(errors,[]);const report={dimensions:dims,cpu:s.hardware.cpu.map(c=>c.Name),gpus:s.hardware.gpus.map(g=>({name:g.name,pci:g.pci,sensors:!!g.sensors})),memorySlots:s.hardware.memory.length,stableNodesAndPositions:true,networkCards:3,manualInputVerified:true,feeAddressesVerified:true,floatingWindowVerified:true,closeToFloatingVerified:true,performanceControlVerified:true,nativeQtcChecks:16,signedReleaseVerified:true,noMiningExecuted:true,poolAccountLiveVerified:true,roundedHashFirstMiniVerified:true,defaultTemperature90:true,hashWindowDisplayVerified:true,poolPresetsAndBackupsVerified:true,workbenchActionsEnlarged:true,kernelChoiceVerified:true,workbenchLogFillAndScrollVerified:true,subtleFooterFeeVerified:true,trayHideRestoreVerified:true,fontScale:1.08,kernelProgressAndReadyVerified:true,compactCurveAndHeatVerified:true,benchmarkButtonEnlarged:true,informationLast:true,automaticFeeLabelVerified:true,incomeSourceAvailable:!getState().income.error&&!!getState().income.at,networkSources:getState().network.map(n=>({coin:n.coin,networkHash:n.networkHash,difficulty:n.difficulty,networkAt:n.networkAt,networkStale:n.networkStale,error:n.error})),trackedAssets:getState().information.tracked,errors,checkedAt:new Date().toISOString()};await fs.writeFile(path.join(dir,'live-report.json'),JSON.stringify(report,null,2));}
module.exports={run};
