'use strict';
(()=>{
 const api=window.gozer;if(!api)return;
 const root=document.querySelector('#mining'),el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)GozerI18n.setText(n,text);return n},put=(n,t)=>GozerI18n.setText(n,t),fmt=n=>{if(!Number.isFinite(n))return '—';for(const [v,u]of [[1e12,'TH/s'],[1e9,'GH/s'],[1e6,'MH/s'],[1e3,'kH/s'],[1,'H/s']])if(n>=v||v===1)return(n/v).toFixed(2)+' '+u};
 const modes=el('div','workbench-modes'),box=el('div','dual-workbench');box.id='dual-workbench';root.prepend(modes);modes.after(box);
 let latest,filter='all',busy=false;const cards={};
 async function run(fn){try{return await fn()}catch(e){window.toast?.(e.message)}}
 for(const [mode,label]of [['gpu','GPU挖矿'],['cpu','CPU挖矿'],['dual','GPU＋CPU双挖']]){const b=el('button','',label);b.dataset.mode=mode;b.onclick=()=>run(async()=>{if(busy)return;busy=true;try{if(latest?.config.workbenchMode==='dual')await Promise.all(Object.values(cards).map(c=>c.flush()));else await window.flushMiningSettings?.();const s=await api.workbenchMode(mode);if(typeof configInputs==='function'){state=s;configInputs();render()}update(s)}finally{busy=false}});modes.append(b)}
 const note=el('span','mode-note','独立任务 · 独立统计');modes.append(note);
 const toolbar=el('div','dual-toolbar'),startAll=el('button','primary','▶ 启动全部'),stopAll=el('button','danger','■ 停止全部');
 const notice=el('span','dual-notice','设置自动保存，手动启动挖矿');toolbar.append(notice,startAll,stopAll);box.append(toolbar);
 for(const [id,label]of [['gpu','GPU 矿池账本'],['cpu','CPU 矿池账本']]){const button=el('button','',label);button.onclick=()=>run(()=>window.openPoolAccount(id));toolbar.append(button)}
 const grid=el('div','dual-grid');box.append(grid);
 const options=(select,items)=>{const key=JSON.stringify(items);if(select.dataset.options===key)return;select.dataset.options=key;select.replaceChildren(...items.map(([value,label])=>{const o=el('option','',label);o.value=value;return o}))};
 const label=(text,control)=>{const l=el('label');l.append(el('span','',text),control);return l};
 function input(placeholder,type='text'){const n=el('input');n.type=type;n.placeholder=placeholder;n.setAttribute('aria-label',placeholder);n.spellcheck=false;return n}
 function make(id){
  const c={id,dirty:false,history:new GozerTelemetry.HashHistory()},card=c.node=el('article','dual-card '+id);card.dataset.task=id;grid.append(card);
  const head=el('div','dual-head');head.append(el('b','task-kind',id.toUpperCase()));c.coin=el('select','task-coin');c.coin.setAttribute('aria-label',id+' 币种');options(c.coin,(id==='cpu'?['ZCD','BNT']:['PRL','QTC','NOID','YSR']).map(v=>[v,v]));c.kernel=el('select','task-kernel');c.kernel.setAttribute('aria-label',id+' 挖矿内核');c.install=el('button','task-install','下载内核');c.status=el('span','task-status','待机');head.append(c.coin,c.kernel,c.install,c.status);card.append(head);
  const metrics=el('div','dual-metrics');const rate=el('div');rate.append(el('small','','实时算力'),c.rate=el('strong','task-rate','—'));const mean=el('div');mean.append(c.meanLabel=el('small','','5分钟均值'),c.mean=el('b','','—'),c.quality=el('small','quality','等待采样'));const chart=el('div','dual-chart');c.svg=document.createElementNS('http://www.w3.org/2000/svg','svg');c.svg.setAttribute('viewBox','0 0 680 52');c.svg.setAttribute('preserveAspectRatio','none');c.path=document.createElementNS(c.svg.namespaceURI,'path');c.svg.append(c.path);chart.append(c.svg,c.shares=el('small','','接受 — / 拒绝 —'));metrics.append(rate,mean,chart);card.append(metrics);
  const connection=el('div','dual-connection');c.wallet=input(id==='cpu'?'02 永久收款地址':'主网收款地址');c.pool=input('矿池地址');connection.append(c.wallet,c.pool);card.append(connection);
  const perf=el('div','dual-performance');c.performance=input('性能预算','range');c.performance.min=50;c.performance.max=100;c.performance.step=1;c.budget=el('b');perf.append(c.budget,c.performance);if(id==='cpu'){c.threads=input('线程数','number');c.threads.min=1;c.threads.max=1024;perf.append(label('线程',c.threads));}else{c.devices=el('div','dual-devices');perf.append(c.devices)}card.append(perf);if(id==='cpu'){c.memory=el('div','dual-memory note');card.append(c.memory);}
  if(id==='cpu'){c.tune=el('button','','自动调优');c.memory.after(c.tune);c.tune.onclick=()=>run(async()=>{if(latest.bntTuning?.running)return api.bntTuneCancel();await api.bntTune('cpu');c.dirty=false;c.key=null;update(await api.bootstrap())})}c.detail=el('details','dual-settings');c.detail.append(el('summary','','矿池 / 设备设置'));const fields=el('div','dual-fields');c.worker=input('矿机名');c.preset=el('select');c.preset.setAttribute('aria-label','矿池预设');c.window=el('select');options(c.window,[[5,'5分钟'],[10,'10分钟']]);fields.append(label('矿机名',c.worker),label('主矿池',c.preset),label('算力周期',c.window));c.backups=[];for(let i=0;i<2;i++){const b=input('备用 '+(i+1));const list=el('datalist');list.id='dual-'+id+'-backups-'+i;b.setAttribute('list',list.id);c.backups.push(b);fields.append(label('备用 '+(i+1),b),list)}if(id==='cpu'){c.password=input('矿池密码');fields.append(label('矿池密码',c.password));}c.hardware=el('div','dual-hardware');c.detail.append(fields,c.hardware);card.append(c.detail);
  const foot=el('div','dual-actions');c.start=el('button','primary','▶ 启动');c.stop=el('button','danger','■ 停止');c.note=el('span','task-note');foot.append(c.note,c.start,c.stop);card.append(foot);
  c.progress=el('progress');c.progress.max=100;c.progress.hidden=true;card.append(c.progress);
  c.error=el('div','dual-error');c.error.hidden=true;card.append(c.error);
  c.edits=new Set();c.saved=false;
  c.autosave=new GozerAutosave.Queue(async values=>{
   const cfg=latest.dual.tasks[id].config,coin=cfg.coin,patch={};
   for(const [key,value]of Object.entries(values)){
    if(key==='wallet')patch.wallets={...cfg.wallets,[coin]:value};
    else if(key==='pool')patch.pools={...cfg.pools,[coin]:value};
    else if(key==='kernel')patch.kernels={...cfg.kernels,[coin]:value};
    else if(key==='backups')patch.poolBackups={...cfg.poolBackups,[coin]:value};
    else patch[key]=value;
   }
   await api.taskSave(id,patch);latest=await api.bootstrap();c.saved=true;
  },q=>{
   c.dirty=q.dirty||c.edits.size>0;
   if(q.error)window.toast?.('设置未保存：'+q.error.message);
   if(!c.dirty&&!q.error&&c.saved){c.key=null;window.toast?.(id.toUpperCase()+' · 设置已保存')}
   if(latest)update(latest);
  });
  const watch=(n,key,read)=>{if(!n)return;n.addEventListener('input',()=>{c.edits.add(n);c.dirty=true;updateControls(c)});n.addEventListener('change',()=>{c.edits.delete(n);c.autosave.set(key,read())})};
  watch(c.kernel,'kernel',()=>c.kernel.value);watch(c.wallet,'wallet',()=>c.wallet.value.trim());watch(c.pool,'pool',()=>c.pool.value.trim());watch(c.worker,'worker',()=>c.worker.value.trim());watch(c.window,'hashWindowMinutes',()=>+c.window.value);watch(c.threads,'cpuThreads',()=>+c.threads.value);watch(c.password,'zcdPassword',()=>c.password.value);
  for(const n of c.backups)watch(n,'backups',()=>c.backups.map(n=>n.value.trim()).filter(Boolean));
  watch(c.performance,'performance',()=>+c.performance.value);
  c.performance.addEventListener('input',()=>{if(c.threads)c.threads.value=c.coin.value==='BNT'?GozerPerformance.bntThreadBudget(latest.bntThreadLimit,+c.performance.value):GozerPerformance.cpuThreadBudget(latest.cpuDevice,+c.performance.value);put(c.budget,GozerPerformance.describe(+c.performance.value).text)});
  c.performance.addEventListener('change',()=>{if(c.threads)c.autosave.set('cpuThreads',+c.threads.value)});
  c.flush=async()=>{for(const n of [...c.edits])n.dispatchEvent(new Event('change'));await c.autosave.flush()};
  c.coin.onchange=()=>run(async()=>{const coin=c.coin.value;try{await c.flush();await api.taskSave(id,{coin,cpuThreads:0});c.dirty=false;c.key=null;update(await api.bootstrap());window.toast?.('设置已保存')}catch(e){c.coin.value=latest.dual.tasks[id].config.coin;throw e}});
  c.preset.onchange=()=>{if(c.preset.value){c.pool.value=c.preset.value;c.pool.dispatchEvent(new Event('change'))}};
  c.start.onclick=()=>run(async()=>{await c.flush();await api.taskStart(id)});c.stop.onclick=()=>run(()=>api.taskStop(id));c.install.onclick=()=>run(async()=>{await c.flush();await api.taskInstall(id);update(await api.bootstrap())});
  return c;
 }
 cards.gpu=make('gpu');cards.cpu=make('cpu');
 const logs=el('article','dual-logs'),logHead=el('div','dual-log-head');logHead.append(el('b','','运行日志'));for(const [v,title]of [['all','全部'],['gpu','GPU'],['cpu','CPU'],['error','错误']]){const b=el('button','',title);b.dataset.filter=v;b.onclick=()=>{filter=v;renderLogs()};logHead.append(b)}const followLabel=el('label'),follow=el('input');follow.type='checkbox';follow.checked=true;followLabel.append(follow,el('span','','跟随'));logHead.append(followLabel);logs.append(logHead);const logList=el('div','dual-log-list');logs.append(logList);box.append(logs);
 startAll.onclick=()=>run(async()=>{await Promise.all(Object.values(cards).map(c=>c.flush()));const results=await api.tasksStart();const errors=results.filter(r=>!r.ok);if(errors.length)throw Error(errors.map(r=>r.id.toUpperCase()+': '+r.error).join('；'))});stopAll.onclick=()=>run(()=>api.tasksStop());
 function updateControls(c){const t=latest?.dual?.tasks[c.id];if(!t)return;const locked=(t.busy&&!c.autosave.busy)||latest.bntTuning?.running,valid=!!c.wallet.value.trim()&&(c.coin.value!=='ZCD'||GozerZcdAddress.validAddress(c.wallet.value.trim()))&&!!c.pool.value.trim();for(const n of c.node.querySelectorAll('input,select'))n.disabled=locked||n.dataset.unavailable==='true';c.install.disabled=locked;c.start.disabled=(c.coin.value==='BNT'&&(!t.fee?.addresses?.BNT||!latest.bntThreadLimit||+c.threads.value>latest.bntThreadLimit))||locked||!valid||!t.kernel.installed||(c.id==='gpu'?!c.devices.querySelector('input:checked'):!latest.cpuDevice);c.stop.disabled=!locked||t.miner.installing;if(c.tune){c.tune.hidden=c.coin.value!=='BNT'||t.kernel.adapter==='bnt-seine';put(c.tune,latest.bntTuning?.running?'取消调优':'自动调优');c.tune.disabled=!latest.bntTuning?.running&&(c.dirty||!latest.ready||!t.kernel.installed||Object.values(latest.dual.tasks).some(v=>v.busy));}put(c.note,c.autosave.error?'设置未保存，请检查输入':c.autosave.busy?'正在保存…':c.dirty?'修改后自动保存':c.saved?'设置已保存':t.kernel.installed?t.kernel.version:'内核未安装');put(c.install,t.kernel.installed?'重新下载':'安装内核');if(c.coin.value==='BNT'&&!t.fee?.addresses?.BNT)put(c.note,'BNT 服务费地址待配置');put(c.budget,GozerPerformance.describe(+c.performance.value).text);c.wallet.setAttribute('aria-invalid',String(!!c.wallet.value&&!valid));}
 function update(s){latest=s;if(!s?.dual)return;const isDual=s.config.workbenchMode==='dual';root.classList.toggle('dual-mode',isDual);box.hidden=!isDual;const mode=isDual?'dual':['ZCD','BNT'].includes(s.config.coin)?'cpu':'gpu';for(const b of modes.querySelectorAll('button')){b.classList.toggle('active',b.dataset.mode===mode);b.disabled=!s.ready;}if(!isDual)return;
  for(const c of Object.values(cards)){
   const t=s.dual.tasks[c.id],cfg=t.config,m=t.miner,coin=cfg.coin;const key=JSON.stringify(cfg);
   if(c.key!==key&&!c.dirty){c.key=key;c.coin.value=coin;options(c.kernel,t.kernel.options.map(o=>[o.id,o.label]));c.kernel.value=cfg.kernels[coin];c.wallet.value=cfg.wallets[coin]||'';c.pool.value=cfg.pools[coin]||'';c.worker.value=cfg.worker;c.window.value=cfg.hashWindowMinutes;c.performance.value=cfg.performance;if(c.threads){c.threads.max=coin==='BNT'?s.bntThreadLimit||1:s.cpuDevice?.logical||1024;c.threads.value=cfg.cpuThreads||(coin==='BNT'?GozerPerformance.bntThreadBudget(s.bntThreadLimit,cfg.performance):GozerPerformance.cpuThreadBudget(s.cpuDevice,cfg.performance));}if(c.password)c.password.value=cfg.zcdPassword;c.backups.forEach((n,i)=>n.value=cfg.poolBackups[coin]?.[i]||'');options(c.preset,[['','自定义'],...t.pools.map(p=>[p.url,p.label])]);c.preset.value=t.pools.some(p=>p.url===c.pool.value)?c.pool.value:'';for(const list of c.node.querySelectorAll('datalist'))list.replaceChildren(...t.pools.map(p=>{const o=el('option');o.value=p.url;o.label=p.label;return o}));}
   if(c.threads){c.threads.max=coin==='BNT'?s.bntThreadLimit||1:s.cpuDevice?.logical||1024;if(!c.dirty&&!t.busy&&!cfg.cpuThreads)c.threads.value=coin==='BNT'?GozerPerformance.bntThreadBudget(s.bntThreadLimit,+c.performance.value):GozerPerformance.cpuThreadBudget(s.cpuDevice,+c.performance.value);c.memory.hidden=coin!=='BNT';if(coin==='BNT'){const b=s.bntMemory||{},g=v=>(Number(v||0)/1073741824).toFixed(1);put(c.memory,'RAM '+g(b.totalBytes)+' / 可用 '+g(s.hardware?.metrics?.freeMemory)+' GiB · 系统预留 '+g(b.reserveBytes)+' GiB · 上限 '+s.bntThreadLimit+' T');}}
   const gpus=s.hardware?.gpus||[];if(c.devices){const key=gpus.map(g=>g.id).join('|');if(c.devices.dataset.key!==key){c.devices.dataset.key=key;c.devices.replaceChildren(...gpus.map((g,i)=>{const n=input(g.name,'checkbox');n.value=g.id;n.dataset.unavailable=String(!g.pci||!['NVIDIA','AMD'].includes(g.vendor));n.checked=cfg.selected.includes(g.id);n.onchange=()=>{c.autosave.set('selected',[...c.devices.querySelectorAll('input:checked')].map(n=>n.value))};const l=label('GPU '+i,n);l.title=g.name;return l}))}if(!c.dirty)for(const n of c.devices.querySelectorAll('input'))n.checked=cfg.selected.includes(n.value);}
   const matching=m.session?.coin===coin&&m.session.performance===cfg.performance&&m.session.kernelId===t.kernel.id&&(c.id==='cpu'?m.session.cpuThreads===(cfg.cpuThreads||(coin==='BNT'?GozerPerformance.bntThreadBudget(s.bntThreadLimit,cfg.performance):GozerPerformance.cpuThreadBudget(s.cpuDevice,cfg.performance))):[...(m.session.selected||[])].sort().join() === [...cfg.selected].sort().join());const total=c.history.update(matching?m:{status:'idle',jobs:[],session:null});put(c.rate,fmt(total));put(c.mean,fmt(matching?m.hashAverage?.hash:null));put(c.meanLabel,cfg.hashWindowMinutes+'分钟均值');const avg=matching?m.hashAverage:null;put(c.quality,avg?(!avg.running?'已停止':!avg.fresh||avg.retained?'上次均值':avg.complete?'已结算':'本期暂估')+' · '+Math.round(avg.coverage*100)+'%':'等待采样');c.path.setAttribute('d',c.history.geometry().line);const shares=m.jobs.map(j=>j.shares||j.telemetry).filter(v=>Number.isFinite(v?.accepted));put(c.shares,'接受 '+(shares.length?shares.reduce((n,v)=>n+v.accepted,0):'—')+' / 拒绝 '+(shares.length?shares.reduce((n,v)=>n+(v.rejected||0),0):'—'));
   put(c.status,m.status==='running'&&m.connection&&m.connection.stage!=='work'?m.connection.message:t.pending?'处理中':({idle:m.session?'已停止':'待机',starting:'启动中',running:t.fee.phase==='service'?'服务收款时段':'运行中',stopping:'停止中'}[m.status]));c.node.classList.toggle('running',m.status==='running');
   const h=s.hardware,metrics=h?.metrics,valid=metrics&&Date.now()-metrics.at<10000;if(c.id==='cpu'){put(c.hardware,(s.cpuDevice?.name||'CPU')+' · '+(s.cpuDevice?.cores||'—')+' 核 / '+(s.cpuDevice?.logical||'—')+' 线程 · '+(valid?'CPU '+Number(metrics.cpuLoad).toFixed(0)+'% · RAM '+((metrics.totalMemory-metrics.freeMemory)/1073741824).toFixed(1)+' GiB':'等待读取'));}else{const sig=gpus.map(g=>g.id).join('|');if(c.hardware.dataset.key!==sig){c.hardware.dataset.key=sig;c.hardware.replaceChildren(...gpus.map(g=>el('div','dual-device-stat')))}gpus.forEach((g,i)=>{const n=c.hardware.children[i],s=g.sensors&&Date.now()-g.sensors.at<10000?g.sensors:null;put(n,g.name+' · '+(Number.isFinite(s?.load)?s.load+'%':'—')+' · '+(Number.isFinite(s?.temp)?s.temp+'°C':'—')+' · '+(Number.isFinite(s?.power)?s.power.toFixed(1)+' W':'—'));n.classList.toggle('hot',Number.isFinite(s?.temp)&&s.temp>=cfg.temperature)})}
   const p=m.installation;c.progress.hidden=!m.installing;if(p?.total)c.progress.value=p.received/p.total*100;else c.progress.removeAttribute('value');c.error.hidden=p?.stage!=='error';if(!c.error.hidden)put(c.error,p.error);if(m.installing)put(c.note,p.stage+' '+(p.total?Math.round(p.received/p.total*100)+'%':''));updateControls(c);if(m.installing)put(c.note,({connecting:'连接下载源',downloading:'下载内核',verifying:'校验安装包',extracting:'解压内核',checking:'校验可执行文件'}[p.stage]||p.stage)+' '+(p.total?Math.round(p.received/p.total*100)+'%':''));
  }
  startAll.disabled=Object.values(cards).every(c=>c.start.disabled)||!s.ready;stopAll.disabled=!Object.values(s.dual.tasks).some(t=>t.busy&&!t.miner.installing);put(notice,'GPU / CPU 独立启停 · 不同算法不合计算力');renderLogs();
 }
 function renderLogs(){if(!latest)return;for(const b of logHead.querySelectorAll('button'))b.classList.toggle('active',b.dataset.filter===filter);const rows=latest.logs.filter(r=>filter==='all'||filter==='error'?filter==='all'||/错误|失败|error|fail/i.test(r.type+' '+r.text):r.task===filter).slice(-100);const key=filter+':'+rows.at(-1)?.id+':'+rows.length;if(logList.dataset.key===key)return;logList.dataset.key=key;const top=logList.scrollTop;logList.replaceChildren(...rows.map(r=>{const row=el('div','dual-log-row');row.append(el('time','',new Date(r.at).toLocaleTimeString('en-GB')),el('b','',r.task?'['+r.task.toUpperCase()+'·'+r.coin+']':r.type),el('span','',r.text));row.title=r.text;return row}));logList.scrollTop=follow.checked?logList.scrollHeight:top;}
 window.renderDual=update;api.subscribe(update);api.bootstrap().then(update);setInterval(()=>{if(latest?.config.workbenchMode==='dual'&&root.classList.contains('active'))update(latest)},1000);
})();
