'use strict';
(()=>{
 const panel=node('section','view');panel.id='kernels';const bar=node('div','section-bar');bar.append(node('b','','币种与内核库'));const back=node('button','','返回工作台');back.onclick=()=>showView('mining');bar.append(back);const note=node('p','note','挖矿期间可查看其他币种和安装其他内核；当前任务继续运行。');const tabs=node('div','library-tabs'),body=node('div','library-body');panel.append(bar,note,tabs,body);$('main').append(panel);
 const stages={connecting:'连接下载源',downloading:'下载内核',verifying:'校验安装包',extracting:'解压内核',checking:'校验可执行文件',ready:'可用内核',error:'安装失败 · 可重试',idle:'尚未安装'};
 let coin='NOID',key='',rows=new Map();
 const busy=()=>state.miner.status!=='idle'||state.serviceFee?.active||state.serviceFee?.switching||Object.values(state.dual?.tasks||{}).some(t=>t.busy);
 window.openKernelLibrary=symbol=>{coin=symbol||state.config.coin;key='';showView('kernels');update(state)};
 $('#kernel-library-open').onclick=()=>openKernelLibrary();
 const extra=node('button','library-mode-link','内核库 ↗');extra.onclick=()=>openKernelLibrary();$('.workbench-modes').append(extra);
 function update(s){if(!s)return;const lib=s.kernelLibrary||[],current=lib.find(c=>c.symbol===coin);if(!current)return;const next=coin+':'+lib.map(c=>c.symbol).join(',');if(key!==next){key=next;tabs.replaceChildren(...lib.map(c=>{const b=node('button',c.symbol===coin?'active':'',c.symbol+' · '+(c.hardware||'GPU'));b.onclick=()=>openKernelLibrary(c.symbol);return b}));body.replaceChildren();rows=new Map();const info=node('div','library-info');info.append(node('b','',current.symbol+' · '+current.name),node('span','muted',current.algorithm));const select=node('button','primary','配置此币种挖矿');select.onclick=()=>action(async()=>{if(busy())throw Error('已有挖矿任务运行。请先停止当前任务，再切换币种启动；下载内核不会停止当前任务。');if(state.config.workbenchMode==='dual'){toast('请返回双挖工作台，在对应 CPU / GPU 任务中选择币种');return}await chooseCoin(coin);showView('mining')});info.append(select);body.append(info);for(const k of current.kernels){const card=node('article','panel library-kernel');const head=node('div','library-head');head.append(node('b','',k.name||'KRig'),node('span','',k.version));const button=node('button','primary','下载并安装');button.onclick=()=>action(async()=>{await api.libraryInstall(coin,k.id);toast('内核安装并校验完成，尚未开始挖矿')},button);head.append(button);const status=node('div','note'),progress=node('progress');progress.max=100;const source=node('p','note',k.bundled?'随附开源核心 · SHA256 校验':(k.adapter==='bnt-seine'?'Seine 原版 GitHub · 内核费 2.5%（bntpool 1%）· 软件服务费 0.5% · SHA256 校验':'官方 GitHub 下载 · SHA256 双重校验'));card.append(head,status,progress,source);body.append(card);rows.set(k.id,{status,progress,button})}if(coin==='BNT'){const card=node('article','panel library-kernel');const head=node('div','library-head');head.append(node('b','','Blocknet Core'),node('span','','0.20.0 · 官方全节点'));const download=node('button','primary','下载 Windows 原版 ↗'),source=node('button','','发布页 / 校验值 ↗');download.onclick=()=>action(()=>api.open('bntOfficialDownload'),download);source.onclick=()=>action(()=>api.open('bntOfficialRelease'),source);head.append(download,source);card.append(head,node('p','note','全节点单挖 · 需要同步区块链；不能作为工作台矿池内核启动。'));const hash=node('small','note','SHA256: f9ca1ac5dd55ddb9af963c44df9152479f05d6c55be3fb2bbf69cfe7d9fa7435');hash.style.overflowWrap='anywhere';card.append(hash);body.append(card)}}
 for(const k of current.kernels){const r=rows.get(k.id);if(!r)continue;const p=k.installation||{};text(r.status,(k.installed?'已安装 · ':'')+(k.installed&&(!p.stage||p.stage==='idle')?'可用内核':(stages[p.stage]||p.stage||''))+(p.stage==='error'?' · '+p.error:'')+(p.received?' · '+num(p.received/1048576,1)+' MB'+(p.total?' / '+num(p.total/1048576,1)+' MB':''):''));r.progress.hidden=!k.installing;if(p.total)r.progress.value=p.received/p.total*100;else r.progress.removeAttribute('value');r.button.disabled=k.installing||lib.some(c=>c.kernels.some(x=>x.installing));text(r.button,k.installing?'下载与校验中…':k.installed?'重新安装':k.bundled?'安装内核':'下载并安装')}
 }
 api.subscribe(update);if(state)update(state);
})();
