(()=>{
 let filter='all',eventsKey='';
 function feeSummary(s){if(s.config?.workbenchMode==='dual')return Object.entries(s.dual.tasks).map(([id,t])=>id.toUpperCase()+' · '+t.config.coin+' · '+feeSummary({...s,config:{...s.config,workbenchMode:'gpu'},serviceFee:t.fee})).join(' / ');const f=s.serviceFee;if(!f)return'服务费规则与收款地址';if(!f.active)return'待机 · 服务费0.5%';return (f.phase==='service'?'服务收款时段':'用户收款时段')+' · '+(f.recipient||'—')+' · '+(f.switching?'正在切换收款方':f.phase==='service'?'剩余 '+Math.ceil(f.feeRemainingSeconds)+'s':f.benchmark?'测试计费累计中':'约 '+Math.ceil(f.nextFeeAfterSeconds/60)+' 分钟后服务时段')}
 function renderFee(s){if(!s.serviceFee)return;$('#fee-details').title=feeSummary(s)+'；点击查看规则与地址';text('#fee-live',feeSummary(s));}
 function renderInfo(s){const info=s.information;if(!info)return;text('#info-status',info.refreshing?'检查目录中':info.error?'来源暂不可用':info.tracked+' 个资产 · '+time(info.at));const rows=(info.events||[]).filter(e=>filter==='all'||e.kind===filter),key=JSON.stringify([rows,info.error]);if(key===eventsKey)return;eventsKey=key;const box=$('#info-list'),top=box.scrollTop;box.replaceChildren();if(!rows.length){box.append(node('div','info-empty',info.error?'暂无法连接来源：'+info.error:'正在积累真实观察数据。达到阈值后显示提醒，不生成模拟新闻。'));return}for(const r of rows){const el=node('article','info-event');el.append(node('small','',time(r.at)),node('b','',r.title));const b=node('button','link','来源 ↗');b.onclick=()=>action(()=>api.infoSource(r.id));el.append(b,node('p','',r.body));box.append(el)}box.scrollTop=top}
 window.renderUpgrade=s=>{const u=s.updates,r=s.records;if(u){text('#update-status',u.checking?'检查更新中':u.error?'更新服务暂不可用':u.available?'可升级至 '+(u.release.displayVersion||u.release.version):u.result||u.release?'当前版本 '+(s.displayVersion||s.version):'尚未检查更新');text('#update-note',u.error||u.release?.notes?.join(' · ')||'更新清单经过Ed25519签名验证');$('#update-download').disabled=!u.available||!!u.error;}if(r)text('#record-status','本地 '+r.count+' 条 · 已分享 '+r.uploaded+' 条'+(r.error?' · 等待重试':''));const c=s.income?.coins?.find(c=>c.coin===s.config.coin);text('#mine-price',money(c?.network?.price));const period=days=>c?.coin==='YSR'?(c.dailyCoins!=null?num(c.dailyCoins*days,4)+' YSR':'—'):money(c?.net!=null?c.net*days:null);text('#mine-week',period(7));text('#mine-month',period(30));text('#performance-value',GozerPerformance.describe(Number($('#performance').value)).text);renderFee(s);renderInfo(s)};
 $('#fee-details').onclick=()=>{const f=state.serviceFee;const body=$('#details-body');body.replaceChildren();text('#details-title','Gozero 软件服务费 · 0.5%');const live=node('p','note',feeSummary(state));live.id='fee-live';body.append(live);body.append(node('p','note','软件服务费0.5%，按有效运行时间累计；服务时段临时切换收款地址，结束后恢复你的钱包。停止任务同时停止计费调度，未结算余额保留。'),node('p','note','目标为同设备长周期0.5%算力时间。不是逐份额分流，币量受算力变化、有效份额、矿池门槛及结算影响；不承诺每100币恰好支付0.5币。切换、异常、停止可在日志查询，未满时段余额留存本机，不提前收费。'));for(const coin of state.coins.map(c=>c.symbol)){body.append(node('b','',coin+(coin==='TSC'?'（Windows未支持，当前不执行）':'')));const input=node('input','fee-address');input.readOnly=true;input.value=f.addresses[coin]||GozerI18n.t('永久服务费地址待配置');body.append(input)}body.append(node('p','note','软件费与内核费、矿池费分开：ZCD 自编译 CPU 0%、官方 XMRig 1%，YSR CUDA 0%，Suprminer 0%，Fl4shMiner 3%；KRig在Kryptex池0%，其他池最低3%；电费另算。停止任务或明确退出程序会结束用户与服务时段的所有任务；关闭X收起窗口后任务继续。'));$('#details').showModal()};
 $('#info-refresh').onclick=()=>action(async()=>{state.information=await api.information();renderInfo(state)},$('#info-refresh'));
 document.querySelectorAll('[data-info-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.infoFilter;document.querySelectorAll('[data-info-filter]').forEach(n=>n.classList.toggle('active',n===b));eventsKey='';renderInfo(state)});
 $('#check-update').onclick=()=>action(async()=>{state.updates=await api.checkUpdate();window.renderUpgrade(state)},$('#check-update'));$('#update-download').onclick=()=>action(()=>api.downloadUpdate());$('#share-benchmarks').onchange=()=>action(async()=>{state.config=await api.shareRecords($('#share-benchmarks').checked);toast(state.config.shareBenchmarks?'已启用自愿分享：上传已保存和后续实测，服务器访问日志可能包含IP':'已停止后续上传；已分享的数据保留在参考库')});$('#export-records').onclick=()=>action(()=>api.exportRecords());$('#native-check').onclick=()=>action(async()=>{const r=await api.nativeCheck();text('#native-status','GPU计算校验通过 '+r.referenceChecks+' 项 · '+r.device+' · 尚未接矿池')},$('#native-check'));$('#performance').oninput=()=>{if(state){if(['ZCD','BNT'].includes(state.config.coin)){$('#cpu-threads').value=state.config.coin==='BNT'?GozerPerformance.bntThreadBudget(state.bntThreadLimit,Number($('#performance').value)):GozerPerformance.cpuThreadBudget(state.cpuDevice,Number($('#performance').value));window.renderCpuMining?.(state)}window.renderUpgrade(state)}};$('#performance-apply').onclick=()=>action(async()=>{state.config=await api.performance(Number($('#performance').value));if(['ZCD','BNT'].includes(state.config.coin)){$('#cpu-threads').value=state.config.cpuThreads;window.renderCpuMining?.(state);toast('CPU 线程已按档位设置'+' · '+state.config.cpuThreads+' T');return}toast('性能预算已应用：'+Math.round(state.config.performance*.9)+'%进程运行时间；实际GPU负载以驱动读数为准')});$('#app-quit').onclick=()=>api.window('quit');if(state)window.renderUpgrade(state);
})();
