(()=>{
 let filter='all',eventsKey='',devicesKey='',current=null;
 function renderNetwork(s){const parent=$('#network-strip');if(!parent.children.length)for(const c of s.coins.map(c=>c.symbol)){const card=node('div','network-card');card.dataset.coin=c;for(const[label,key]of [[c,'title'],['全网算力','hash'],['当前难度','difficulty'],['参考币价','price']]){const row=node('div',key==='title'?'network-title':'');row.append(node('label','',label),node('b',key,'—'));card.append(row)}parent.append(card)}
 for(const n of s.network||[]){const card=parent.querySelector('[data-coin="'+n.coin+'"]');if(!card)continue;card.classList.toggle('stale',!!n.networkStale);card.classList.toggle('loading',!!n.refreshing);text(card.querySelector('.title'),n.refreshing?'更新中':n.error?'来源异常':n.networkStale?'缓存 / 过期':time(n.networkAt));text(card.querySelector('.hash'),hash(n.networkHash??null,n.networkUnit||'H/s'));text(card.querySelector('.difficulty'),n.difficulty>1e10?n.difficulty.toExponential(4):num(n.difficulty,3));text(card.querySelector('.price'),n.price===null||n.price===undefined?'—':'$'+num(n.price,n.price<1?5:3)+(n.priceStale?' *':''));card.title=[n.networkSource,'网络数据：'+(n.networkAt?new Date(n.networkAt).toLocaleString():'未获取'),n.basis,n.error||''].filter(Boolean).join('\n')}
 }
 function manualForm(s){const devices=selected(),key=devices.map(d=>d.id).join('|');if(key===devicesKey)return;devicesKey=key;const parent=$('#manual-device'),prev=parent.value;parent.replaceChildren(...devices.map(d=>{const o=node('option','',d.name.replace(/^NVIDIA GeForce |^AMD Radeon /,''));o.value=d.id;return o}));if(devices.some(d=>d.id===prev))parent.value=prev;loadManual()}
 function loadManual(){if(!current)return;const coin=$('#estimate-coin').value,id=$('#manual-device').value,r=current.config.manualInputs?.[coin]?.[id];const unit=$('#manual-unit');if(coin==='TSC'){unit.replaceChildren();const o=node('option','','N/s');o.value='1';unit.append(o)}else if(unit.options.length<2){unit.replaceChildren();for(const[v,t]of [[1,'H/s'],[1e6,'MH/s'],[1e9,'GH/s'],[1e12,'TH/s']]){const o=node('option','',t);o.value=v;unit.append(o)}}const multiplier=coin==='TSC'?1:r?.hash>=1e12?1e12:r?.hash>=1e9?1e9:r?.hash>=1e6?1e6:coin==='PRL'?1e12:1e9;unit.value=String(multiplier);$('#manual-hash').value=r?r.hash/multiplier:'';$('#manual-power').value=r?.watts??'';}
 function feeSummary(s){const f=s.serviceFee;if(!f)return'服务费规则与收款地址';if(!f.active)return'待机 · 挖矿与收益测试统一计费';return (f.phase==='service'?'服务收款时段':'用户收款时段')+' · '+(f.recipient||'—')+' · '+(f.switching?'正在切换收款方':f.phase==='service'?'剩余 '+Math.ceil(f.feeRemainingSeconds)+'s':f.benchmark?'测试计费累计中':'约 '+Math.ceil(f.nextFeeAfterSeconds/60)+' 分钟后服务时段')}
 function renderFee(s){const f=s.serviceFee;if(!f)return;const active=f.active;$('#fee-details').title=feeSummary(s)+'；点击查看规则与地址';text('#fee-live',feeSummary(s));$('#save-manual').disabled=active||s.miner.status!=='idle';$('#clear-manual').disabled=$('#save-manual').disabled;
 for(const c of s.income?.coins||[]){const card=$('#profit-cards').querySelector('[data-coin="'+c.coin+'"]');if(card){card.title='软件费：0.5%；矿工费：'+(c.kernelFeeRate===null?'未确认':num(c.kernelFeeRate*100,1)+'%')+'；矿池费：'+s.config.poolFee+'%。\n'+(c.rows[0]?.basis||'来源暂不完整');text(card.querySelector('label'),'预计净收益 / 日 · 已扣软件费')}}
 }
 function renderInfo(s){const info=s.information;if(!info)return;text('#info-status',info.refreshing?'检查目录中':info.error?'来源暂不可用':info.tracked+' 个资产 · '+time(info.at));const rows=(info.events||[]).filter(e=>filter==='all'||e.kind===filter),key=JSON.stringify([rows,info.error]);if(key===eventsKey)return;eventsKey=key;const box=$('#info-list'),top=box.scrollTop;box.replaceChildren();if(!rows.length){box.append(node('div','info-empty',info.error?'暂无法连接来源：'+info.error:'正在积累真实观察数据。达到阈值后显示提醒，不生成模拟新闻。'));return}for(const r of rows){const el=node('article','info-event');el.append(node('small','',time(r.at)),node('b','',r.title));const b=node('button','link','来源 ↗');b.onclick=()=>action(()=>api.infoSource(r.id));el.append(b,node('p','',r.body));box.append(el)}box.scrollTop=top}
 window.renderUpgrade=s=>{current=s;const u=s.updates,r=s.records;if(u){text('#update-status',u.checking?'检查更新中':u.error?'更新服务暂不可用':u.available?'可升级至 '+(u.release.displayVersion||u.release.version):u.result||u.release?'当前版本 '+(s.displayVersion||s.version):'尚未检查更新');text('#update-note',u.error||u.release?.notes?.join(' · ')||'更新清单经过Ed25519签名验证');$('#update-download').disabled=!u.available||!!u.error;}if(r)text('#record-status','本地 '+r.count+' 条 · 已分享 '+r.uploaded+' 条'+(r.error?' · 等待重试':''));const c=s.income?.coins?.find(c=>c.coin===s.config.coin);text('#mine-price',money(c?.network?.price));text('#mine-week',money(c?.net!=null?c.net*7:null));text('#mine-month',money(c?.net!=null?c.net*30:null));text('#performance-value',GozerPerformance.describe(Number($('#performance').value)).text);renderNetwork(s);manualForm(s);renderFee(s);renderInfo(s)};
 $('#estimate-coin').onchange=loadManual;$('#manual-device').onchange=loadManual;
 $('#save-manual').onclick=()=>action(async()=>{const coin=$('#estimate-coin').value,id=$('#manual-device').value;if(!id)throw Error('先选择显卡');if($('#manual-hash').value==='')throw Error('请输入实际算力');const hash=Number($('#manual-hash').value)*Number($('#manual-unit').value),watts=$('#manual-power').value===''?null:Number($('#manual-power').value),manualInputs=structuredClone(state.config.manualInputs);manualInputs[coin][id]={hash,unit:coin==='TSC'?'N/s':'H/s',watts};await save({manualInputs});toast('已按输入算力重新测算；实测结果存在时优先使用实测')});
 $('#clear-manual').onclick=()=>action(async()=>{const manualInputs=structuredClone(state.config.manualInputs);delete manualInputs[$('#estimate-coin').value][$('#manual-device').value];await save({manualInputs});loadManual()});
 $('#fee-details').onclick=()=>{const f=state.serviceFee;const body=$('#details-body');body.replaceChildren();text('#details-title','Gozero 软件服务费 · 0.5%');const live=node('p','note',feeSummary(state));live.id='fee-live';body.append(live);body.append(node('p','note','挖矿与收益测试自动按0.5%计费，无需勾选。约199分钟有效GPU运行时间累计最多60秒服务时段。服务时段临时将矿工收款地址切换为下列地址，再恢复你的钱包；切换有重连开销。短测试的零碎服务时间保存于本机；累计满60秒后，在下一次任务开始先结算，再开始完整60秒采样。停止任务同时停止计费调度。'),node('p','note','目标为同设备长周期0.5%算力时间。不是逐份额分流，币量受算力变化、有效份额、矿池门槛及结算影响；不承诺每100币恰好支付0.5币。切换、异常、停止可在日志查询，未满时段余额留存本机，不提前收费。'));for(const coin of state.coins.map(c=>c.symbol)){body.append(node('b','',coin+(coin==='TSC'?'（Windows未支持，当前不执行）':'')));const input=node('input','fee-address');input.readOnly=true;input.value=f.addresses[coin];body.append(input)}body.append(node('p','note','软件费与内核费、矿池费分开：Suprminer 0%，Fl4shMiner 3%；KRig在Kryptex池0%，其他池最低3%；电费另算。停止任务或明确退出程序会结束用户与服务时段的所有任务；关闭X收起窗口后任务继续。'));$('#details').showModal()};
 $('#info-refresh').onclick=()=>action(async()=>{state.information=await api.information();renderInfo(state)},$('#info-refresh'));
 document.querySelectorAll('[data-info-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.infoFilter;document.querySelectorAll('[data-info-filter]').forEach(n=>n.classList.toggle('active',n===b));eventsKey='';renderInfo(state)});
 $('#check-update').onclick=()=>action(async()=>{state.updates=await api.checkUpdate();window.renderUpgrade(state)},$('#check-update'));$('#update-download').onclick=()=>action(()=>api.downloadUpdate());$('#share-benchmarks').onchange=()=>action(async()=>{state.config=await api.shareRecords($('#share-benchmarks').checked);toast(state.config.shareBenchmarks?'已启用自愿分享：上传已保存和后续实测，服务器访问日志可能包含IP':'已停止后续上传；已分享的数据保留在参考库')});$('#export-records').onclick=()=>action(()=>api.exportRecords());$('#native-check').onclick=()=>action(async()=>{const r=await api.nativeCheck();text('#native-status','GPU计算校验通过 '+r.referenceChecks+' 项 · '+r.device+' · 尚未接矿池')},$('#native-check'));$('#performance').oninput=()=>{if(state)window.renderUpgrade(state)};$('#performance-apply').onclick=()=>action(async()=>{state.config=await api.performance(Number($('#performance').value));toast('性能预算已应用：'+Math.round(state.config.performance*.9)+'%进程运行时间；实际GPU负载以驱动读数为准')});$('#app-quit').onclick=()=>api.window('quit');if(state)window.renderUpgrade(state);
})();
