'use strict';
const fs=require('node:fs/promises'),path=require('node:path');
const {validChoice}=require('./kernel-catalog.cjs');
const {poolChoices,recommendedBackups}=require('./pool-catalog.cjs');
const DEFAULT={version:1,cpuThreads:0,zcdPassword:'x',noidConnection:'auto',noidConnectionVersion:2,poolRoutingVersion:1,ysrPoolVersion:1,zcdPoolVersion:1,hashWindowMinutes:5,poolBackups:{ZCD:[],YSR:[],NOID:recommendedBackups('NOID',poolChoices('NOID')[0].url),PRL:recommendedBackups('PRL',poolChoices('PRL')[0].url),QTC:recommendedBackups('QTC',poolChoices('QTC')[0].url)},kernels:{ZCD:'auto',YSR:'auto',NOID:'auto',PRL:'auto',QTC:'auto',TSC:'auto'},performance:75,shareBenchmarks:false,theme:'dark',language:'zh-CN',interval:2000,electricity:0.08,poolFee:0,temperature:90,selected:[],coin:'PRL',wallets:{ZCD:'',YSR:'',NOID:'',PRL:'',QTC:'',TSC:''},worker:'Gozer',pools:{ZCD:poolChoices('ZCD')[0].url,YSR:poolChoices('YSR')[0].url,NOID:'stratum+ssl://stratum-apac.suprnova.cc:3341',PRL:'stratum+ssl://prl-sg.kryptex.network:8048',QTC:'stratum+ssl://qtc-sg.kryptex.network:8049'},manualWatts:null,manualInputs:{ZCD:{},YSR:{},NOID:{},PRL:{},QTC:{},TSC:{}}};
function validatePool(value){if(typeof value!=='string'||value.length>240)throw Error('矿池地址无效');const u=new URL(value);if(!['stratum+ssl:','stratum+tcp:'].includes(u.protocol)||!u.hostname||u.username||u.password||u.search||u.hash||(u.pathname&&u.pathname!=='/')||!/^[a-z0-9.:[\]-]+$/i.test(u.hostname))throw Error('矿池需要 stratum+ssl:// 或 stratum+tcp:// 主机:端口');if(!u.port||+u.port<1||+u.port>65535)throw Error('矿池端口无效');return value}
function validate(c){if(!c||typeof c!=='object'||Array.isArray(c))throw Error('配置格式无效');const out=structuredClone(DEFAULT);if(c.language!==undefined){if(!['zh-CN','en','ja','ru'].includes(c.language))throw Error('不支持的界面语言');out.language=c.language}if(c.theme!==undefined){if(!['dark','light'].includes(c.theme))throw Error('主题无效');out.theme=c.theme}for(const[k,min,max]of[['electricity',0,10],['poolFee',0,20],['temperature',50,95]])if(c[k]!==undefined){if(typeof c[k]!=='number'||!Number.isFinite(c[k])||c[k]<min||c[k]>max)throw Error(k+' 超出范围');out[k]=c[k]}if(c.interval!==undefined){if(![1000,2000,3000,5000].includes(c.interval))throw Error('刷新周期无效');out.interval=c.interval}if(c.manualWatts!==undefined){if(c.manualWatts!==null&&(!Number.isFinite(c.manualWatts)||c.manualWatts<1||c.manualWatts>20000))throw Error('整机功耗无效');out.manualWatts=c.manualWatts}if(c.coin!==undefined){if(!['PRL','QTC','TSC','NOID','YSR','ZCD'].includes(c.coin))throw Error('币种无效');out.coin=c.coin}if(c.selected!==undefined){if(!Array.isArray(c.selected)||c.selected.length>32||c.selected.some(x=>typeof x!=='string'||!/^[a-f0-9]{20}$/.test(x)))throw Error('设备选择无效');out.selected=[...new Set(c.selected)]}if(c.worker!==undefined){if(typeof c.worker!=='string'||!/^[A-Za-z0-9_.-]{1,32}$/.test(c.worker))throw Error('矿机名仅支持字母、数字、点、下划线和连字符');out.worker=c.worker}for(const coin of ['PRL','QTC','TSC','NOID','YSR','ZCD'])if(c.wallets?.[coin]!==undefined){const w=c.wallets[coin];if(typeof w!=='string'||w.length>140||(w&&!/^[A-Za-z0-9]+$/.test(w)))throw Error('钱包地址只能包含字母和数字');out.wallets[coin]=w}for(const coin of ['PRL','QTC','NOID','YSR','ZCD'])if(c.pools?.[coin]!==undefined)out.pools[coin]=coin==='ZCD'&&c.pools[coin]===''?'':coin==='YSR'?require('./ysr-protocol.cjs').validateApi(c.pools[coin]):validatePool(c.pools[coin]);// Legacy consent is intentionally ignored; the disclosed 0.5% rate is automatic.

if(c.noidConnection!==undefined){if(!['auto','native','compatible'].includes(c.noidConnection))throw Error('NOID 连接模式无效');out.noidConnection=c.noidConnection}
if(c.hashWindowMinutes!==undefined){if(![5,10].includes(c.hashWindowMinutes))throw Error('算力周期仅支持5或10分钟');out.hashWindowMinutes=c.hashWindowMinutes}
if(c.poolBackups!==undefined&&(!c.poolBackups||typeof c.poolBackups!=='object'||Array.isArray(c.poolBackups)))throw Error('备用矿池格式无效');
for(const coin of ['PRL','QTC','NOID','YSR','ZCD']){
 const backups=c.poolBackups?.[coin]??recommendedBackups(coin,out.pools[coin]);
 if(!Array.isArray(backups)||backups.length>2)throw Error('每币最多两个备用矿池');
 out.poolBackups[coin]=[...new Set(backups.map(coin==='YSR'?require('./ysr-protocol.cjs').validateApi:validatePool))].filter(url=>url!==out.pools[coin]);
 for(const url of [out.pools[coin],...out.poolBackups[coin]].filter(Boolean)){const host=new URL(url).hostname;if(/^(prl|qtc)(?:-[a-z]+)?\.kryptex\.network$/.test(host)&&!host.startsWith(coin.toLowerCase()))throw Error('矿池地址与币种不一致')}
}
if(c.kernels!==undefined){if(!c.kernels||typeof c.kernels!=='object'||Array.isArray(c.kernels))throw Error('内核选择无效');for(const coin of ['PRL','QTC','TSC','NOID','YSR','ZCD'])if(c.kernels[coin]!==undefined){if(coin==='NOID'&&c.kernels[coin]==='gozero-noid-0.2.0'){out.kernels.NOID='auto';continue}if(coin==='YSR'&&['gozero-ysr-0.1.0','gozero-ysr-0.1.1','gozero-ysr-0.1.2'].includes(c.kernels[coin])){out.kernels.YSR='auto';continue}if(!validChoice(coin,c.kernels[coin]))throw Error(coin+' 不支持所选内核');out.kernels[coin]=c.kernels[coin]}}
if(c.manualInputs!==undefined){for(const coin of ['PRL','QTC','TSC','NOID','YSR','ZCD']){const rows=c.manualInputs?.[coin]||{};if(typeof rows!=='object'||Array.isArray(rows)||Object.keys(rows).length>32)throw Error('手动输入数量无效');for(const[id,r]of Object.entries(rows)){if(!/^[a-f0-9]{20}$/.test(id)||!r||!Number.isFinite(r.hash)||r.hash<0||r.hash>1e22||r.unit!==(coin==='TSC'?'N/s':'H/s')||(r.watts!==null&&(!Number.isFinite(r.watts)||r.watts<=0||r.watts>10000)))throw Error('实际算力或功耗输入无效');out.manualInputs[coin][id]={hash:r.hash,unit:r.unit,watts:r.watts}}}}
if(c.zcdPassword!==undefined){if(typeof c.zcdPassword!=='string'||c.zcdPassword.length>100||!/^[-a-zA-Z0-9_.,=:@/ ]*$/.test(c.zcdPassword))throw Error('ZCD 矿池密码格式无效');out.zcdPassword=c.zcdPassword}
if(c.cpuThreads!==undefined){if(!Number.isInteger(c.cpuThreads)||c.cpuThreads<0||c.cpuThreads>1024)throw Error('CPU 线程数无效');out.cpuThreads=c.cpuThreads}
if(out.wallets.ZCD&&!require('./zcd.cjs').validAddress(out.wallets.ZCD))throw Error('ZCD 需要 02 开头的 32 字节永久地址，不能使用一次性地址');
if(out.wallets.YSR&&!require('./ysr-protocol.cjs').validAddress(out.wallets.YSR))throw Error('YSR 地址校验失败，需要有效的 ysr1 主网地址');
if(out.wallets.NOID&&!require('./noid.cjs').validWallet(out.wallets.NOID))throw Error('NOID 地址校验失败，需要有效的 o1 主网 bech32m 地址');
if(out.coin==='NOID'&&out.worker.includes('.'))throw Error('NOID 矿机名不支持点号，请使用字母、数字、下划线或连字符');
if(c.performance!==undefined){if(!Number.isInteger(c.performance)||c.performance<50||c.performance>100)throw Error('性能预算需要50–100');out.performance=c.performance}if(c.shareBenchmarks!==undefined){if(typeof c.shareBenchmarks!=='boolean')throw Error('分享设置无效');out.shareBenchmarks=c.shareBenchmarks}return out}
class ConfigStore{constructor(dir){this.file=path.join(dir,'settings.json');this.value=structuredClone(DEFAULT);this.queue=Promise.resolve()}async load(){try{const raw=JSON.parse(await fs.readFile(this.file,'utf8'));if(raw.noidConnectionVersion!==2){raw.noidConnection='auto';this.notice='NOID 已启用自动连接：原始连接失败后尝试兼容 TCP（非加密）'}if(raw.kernels?.NOID==='gozero-noid-0.2.0'){raw.kernels.NOID='auto';this.notice=[this.notice,'自研 NOID 内核已移除，默认使用 Suprminer'].filter(Boolean).join('；')}if(!raw.poolRoutingVersion){for(const coin of ['PRL','QTC','NOID','YSR','ZCD']){const legacy='stratum+ssl://'+coin.toLowerCase()+'.kryptex.network:'+(coin==='PRL'?8048:8049);if(raw.pools?.[coin]===legacy){raw.pools[coin]=poolChoices(coin)[0].url;this.notice='旧版全球默认矿池已迁移为新加坡节点，可在工作台更改'}}}if(raw.ysrPoolVersion!==1&&[require('./ysr-protocol.cjs').LEGACY_API,require('./ysr-protocol.cjs').LEGACY_API+'/'].includes(raw.pools?.YSR))raw.pools.YSR=poolChoices('YSR')[0].url;if(raw.zcdPoolVersion!==1&&(raw.pools?.ZCD===undefined||raw.pools.ZCD==='')){raw.pools={...raw.pools,ZCD:poolChoices('ZCD')[0].url}}this.value=validate(raw)}catch(e){if(e.code!=='ENOENT')this.warning='配置损坏或版本不兼容，使用默认配置；原文件未删除'}return this.value}save(value){const next=validate(value);this.queue=this.queue.catch(()=>{}).then(async()=>{await fs.mkdir(path.dirname(this.file),{recursive:true});const tmp=this.file+'.tmp';await fs.writeFile(tmp,JSON.stringify(next,null,2),'utf8');await fs.rename(tmp,this.file);this.value=next;return next});return this.queue}}
module.exports={DEFAULT,validate,validatePool,ConfigStore};
