'use strict';
const path=require('node:path'),fs=require('node:fs/promises');
function clampPosition(position,area,width=288,height=218){const x=Number.isFinite(position?.x)?position.x:area.x+area.width-width-18,y=Number.isFinite(position?.y)?position.y:area.y+area.height-height-30;return{x:Math.round(Math.min(Math.max(x,area.x),Math.max(area.x,area.x+area.width-width))),y:Math.round(Math.min(Math.max(y,area.y),Math.max(area.y,area.y+area.height-height)))}}
const {describe}=require('../renderer/performance.js');
function compactState(s){const active=['starting','running','stopping'].includes(s.miner?.status)&&Number.isInteger(s.miner?.session?.performance);const budget=describe(active?s.miner.session.performance:s.config?.performance);const h=s.hardware||{},metrics=Date.now()-(h.metrics?.at||0)<10000?h.metrics:{},known=(h.gpus||[]).filter(g=>g.sensors&&Date.now()-g.sensors.at<10000),loads=known.map(g=>g.sensors.load).filter(Number.isFinite),temps=known.map(g=>g.sensors.temp).filter(Number.isFinite);const coin=s.miner?.status==='running'?(s.miner?.session?.coin||s.config?.coin):s.config?.coin,n=s.network?.find(x=>x.coin===coin),income=s.income?.coins?.find(x=>x.coin===coin),jobs=(s.miner?.jobs||[]).filter(j=>j.status==='running'&&j.telemetry&&Date.now()-j.telemetry.at<20000);const selected=(h.gpus||[]).filter(g=>s.config?.selected?.includes(g.id)),powers=selected.map(g=>g.sensors&&Date.now()-g.sensors.at<10000?g.sensors.power:null);const avg=s.miner?.session?.coin===coin?s.miner?.hashAverage:null;return{deviceLabel:selected.length?selected.length+' GPU · '+selected.map(g=>g.name.replace(/^NVIDIA GeForce |^AMD Radeon /,'')).join(' + '):'尚未选择GPU',power:powers.length&&powers.every(Number.isFinite)?powers.reduce((a,b)=>a+b,0):null,hashAverage:avg,canStop:s.miner?.status!=='idle'||!!s.serviceFee?.active||!!s.serviceFee?.switching,hash:avg?avg.hash:jobs.length?jobs.reduce((v,j)=>v+j.telemetry.hash,0):null,networkHash:n?.networkHash??null,networkStale:n?.networkStale??true,price:n?.price??null,priceStale:n?.priceStale??true,day:income?.net??null,week:income?.net!=null?income.net*7:null,month:income?.net!=null?income.net*30:null,incomeStale:income?.stale??true,performance:budget.percent,performanceMode:budget.mode,performanceLabel:budget.text,performanceActive:active,theme:s.config?.theme||'dark',cpu:metrics.cpuLoad??null,memory:metrics.totalMemory>0?(1-metrics.freeMemory/metrics.totalMemory)*100:null,gpu:loads.length?loads.reduce((a,b)=>a+b,0)/loads.length:null,temperatureLimit:s.config?.temperature||90,gpuTemperature:temps.length?Math.max(...temps):null,cpuTemperature:null,known:known.length,total:(h.gpus||[]).length,status:s.miner?.status||'idle',coin,feePhase:s.serviceFee?.phase||'idle',version:s.version}}
class Floating{
 constructor(electron,dir,restore,onStop,isTest=false){this.e=electron;this.file=path.join(dir,'floating-position.json');this.restore=restore;this.onStop=onStop;this.test=isTest;this.win=null;this.creating=null;this.saved=null;this.latest=null;this.url=require('node:url').pathToFileURL(path.join(__dirname,'../renderer/mini.html')).href}
 async create(){if(this.win&&!this.win.isDestroyed())return this.win;if(this.creating)return this.creating;this.creating=(async()=>{try{this.saved=JSON.parse(await fs.readFile(this.file,'utf8'))}catch{}const display=this.saved&&Number.isFinite(this.saved.x)&&Number.isFinite(this.saved.y)?this.e.screen.getDisplayNearestPoint(this.saved):this.e.screen.getPrimaryDisplay(),pos=clampPosition(this.saved,display.workArea);const w=this.win=new this.e.BrowserWindow({width:288,height:218,x:pos.x,y:pos.y,frame:false,thickFrame:false,show:false,resizable:false,skipTaskbar:true,alwaysOnTop:true,transparent:true,backgroundColor:'#00000000',title:'Gozero助手 · 悬浮监控',icon:path.join(__dirname,'../assets/icon.ico'),webPreferences:{offscreen:this.test,preload:path.join(__dirname,'mini-preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});w.webContents.setWindowOpenHandler(()=>({action:'deny'}));w.webContents.on('will-navigate',e=>e.preventDefault());w.on('close',e=>{if(!this.destroying){e.preventDefault();this.hide()}});w.on('move',()=>{clearTimeout(this.saveTimer);this.saveTimer=setTimeout(()=>{if(!w.isDestroyed()){const[x,y]=w.getPosition();fs.writeFile(this.file,JSON.stringify({x,y})).catch(()=>{})}},400)});await w.loadFile(path.join(__dirname,'../renderer/mini.html'));if(this.latest)this.send(this.latest);return w})();try{return await this.creating}finally{this.creating=null}}
 async show(){this.wantVisible=true;const w=await this.create();if(this.wantVisible&&!this.test)w.showInactive();this.send(this.latest)}
 hide(){this.wantVisible=false;this.win?.hide()}
 send(value){if(value)this.latest=value;if(this.win&&!this.win.isDestroyed()&&this.latest)this.win.webContents.send('mini-state',this.latest)}
 destroy(){this.destroying=true;clearTimeout(this.saveTimer);this.win?.destroy()}
}
module.exports={Floating,compactState,clampPosition};
