'use strict';
const os=require('node:os'),path=require('node:path'),fs=require('node:fs'),{deviceId}=require('./device-selection.cjs');
const {execFile}=require('node:child_process');
const {promisify}=require('node:util');const exec=promisify(execFile);
const {readInventory}=require('./inventory.cjs');
const SMI=path.join(process.env.SystemRoot||'C:\\Windows','System32','nvidia-smi.exe');
const FIELDS=['uuid','name','pci.bus_id','memory.total','driver_version','utilization.gpu','temperature.gpu','power.draw','clocks.current.graphics','clocks.current.memory','fan.speed','pcie.link.gen.current','pcie.link.gen.max','pcie.link.width.current','pcie.link.width.max','memory.used','power.limit'];
const number=v=>v===null||v===undefined||String(v).trim()===''||!Number.isFinite(Number(v))?null:Number(v);
function pci(v){return String(v||'').toLowerCase().match(/([0-9a-f]{2,}:[0-9a-f]{2}\.[0-7])$/)?.[1]||null}
function parseSmi(text){return text.trim().split(/\r?\n/).filter(Boolean).map(line=>{const v=line.split(',').map(x=>x.trim());if(v.length!==FIELDS.length)throw Error('NVIDIA 返回字段数量变化');return{uuid:v[0],name:v[1],pci:pci(v[2]),memoryMiB:number(v[3]),driver:v[4],load:number(v[5]),temp:number(v[6]),power:number(v[7]),clock:number(v[8]),memClock:number(v[9]),fan:number(v[10]),gen:number(v[11]),maxGen:number(v[12]),width:number(v[13]),maxWidth:number(v[14]),usedMiB:number(v[15]),powerLimit:number(v[16]),at:Date.now(),source:'NVIDIA 驱动 / nvidia-smi'}})}
function normalizeInventory(raw){const gpu=(raw.gpus||[]).map(g=>({id:deviceId(g.pnp),name:g.name,pci:pci(g.pci),vendor:/VEN_10DE/i.test(g.pnp)?'NVIDIA':/VEN_1002/i.test(g.pnp)?'AMD':/VEN_8086/i.test(g.pnp)?'Intel':'其他',driver:g.driver,status:g.status,sensors:null,source:'Windows CIM / PnP',deviceId:g.pnp.match(/VEN_[0-9A-F]+&DEV_[0-9A-F]+/i)?.[0]||'—'}));return{gpus:gpu,cpu:raw.cpu||[],memory:raw.memory||[],board:raw.board||[],bios:raw.bios||[],os:raw.os||[],cache:raw.cache||[],warnings:raw.warnings||[],scannedAt:Date.now()}}
function mergeSmi(inventory,rows){for(const row of rows){let g=inventory.gpus.find(g=>g.vendor==='NVIDIA'&&((g.pci&&g.pci===row.pci)||g.sensors?.uuid===row.uuid));if(!g){g={id:deviceId(row.uuid),name:row.name,pci:row.pci,vendor:'NVIDIA',driver:row.driver,source:'NVIDIA 驱动',deviceId:'—'};inventory.gpus.push(g)}if(!g.pci&&row.pci)g.pci=row.pci;g.sensors=row;g.memoryMiB=row.memoryMiB;g.driver=row.driver}return inventory}
function cpuDelta(before,after){return after.map((c,i)=>{const b=before[i];if(!b)return null;const total=Object.keys(c.times).reduce((n,k)=>n+c.times[k]-b.times[k],0);return total>0?Math.max(0,Math.min(100,100*(1-(c.times.idle-b.times.idle)/total))):null})}
class Hardware {
 constructor(onUpdate=()=>{}){this.onUpdate=onUpdate;this.inventory={gpus:[],cpu:[],memory:[],board:[],bios:[],os:[],cache:[],warnings:[],scannedAt:null};this.previous=os.cpus();this.last=null;this.timer=null;this.running=false;this.closed=false;this.pendingScan=null;this.interval=2000;this.lastSensorAt=0;this.sensorError=null}
 async scan(){if(this.pendingScan)return this.pendingScan;this.pendingScan=(async()=>{this.inventory=normalizeInventory(await readInventory());await this.sensors();await this.nvmlInfo();return this.sample()})();try{return await this.pendingScan}finally{this.pendingScan=null}}
 async nvmlInfo(){try{const file=path.join(__dirname,'../vendor/NvmlInfo.exe');const {stdout}=await exec(file,[],{windowsHide:true,timeout:5000,maxBuffer:1024*1024});const names={2:'Kepler',3:'Maxwell',4:'Pascal',5:'Volta',6:'Turing',7:'Ampere',8:'Ada',9:'Hopper',10:'Blackwell',13:'Rubin'};for(const row of JSON.parse(stdout)){const g=this.inventory.gpus.find(g=>g.sensors?.uuid===row.uuid);if(g)Object.assign(g,{cores:row.cores,memoryBusWidth:row.memoryBusWidth,architecture:names[row.architecture]||null,specSource:'NVIDIA NVML 驱动只读接口'})}}catch{this.inventory.warnings.push('NVML 静态规格接口不可用')}}
 async sensors(){if(!fs.existsSync(SMI)){this.sensorError='未安装 NVIDIA 驱动监测接口；其他厂商传感器待适配';return}try{const{stdout}=await exec(SMI,['--query-gpu='+FIELDS.join(','),'--format=csv,noheader,nounits'],{windowsHide:true,timeout:4500,maxBuffer:1024*1024});mergeSmi(this.inventory,parseSmi(stdout));this.lastSensorAt=Date.now();this.sensorError=null}catch(e){this.sensorError='NVIDIA 传感器暂不可用：'+(e.code||'timeout')}}
 sample(){const next=os.cpus(),perCore=cpuDelta(this.previous,next);this.previous=next;const valid=perCore.filter(Number.isFinite);this.last={...this.inventory,metrics:{at:Date.now(),cpuLoad:valid.length?valid.reduce((a,b)=>a+b,0)/valid.length:null,perCore,totalMemory:os.totalmem(),freeMemory:os.freemem(),uptime:os.uptime(),sensorAt:this.lastSensorAt,sensorError:this.sensorError}};this.onUpdate(this.last);return this.last}
 start(){this.closed=false;const tick=async()=>{if(this.closed)return;this.running=true;try{if(!this.pendingScan)await this.sensors();this.sample()}finally{this.running=false;if(!this.closed)this.timer=setTimeout(tick,this.interval)}};tick()}
 stop(){this.closed=true;clearTimeout(this.timer)}
}
module.exports={Hardware,parseSmi,normalizeInventory,mergeSmi,cpuDelta,pci,number};
