'use strict';
const fs=require('node:fs/promises'),path=require('node:path');
const URL='https://pro.gozero.trade/api/state';
class Intelligence{
 constructor(dir,request,onUpdate){this.file=path.join(dir,'intelligence.json');this.request=request;this.onUpdate=onUpdate;this.events=[];this.baseline={};this.quotes=new Map();this.profits=new Map();this.cooldown=new Map();this.at=null;this.error=null;this.initialized=false;this.closed=false;this.pending=null}
 async load(){try{const d=JSON.parse(await fs.readFile(this.file,'utf8'));this.events=Array.isArray(d.events)?d.events.slice(0,150):[];this.baseline=d.baseline||{};this.initialized=!!d.initialized}catch{}}
 add(event,key=event.id){const now=Date.now();if(now-(this.cooldown.get(key)||0)<900000)return;this.cooldown.set(key,now);this.events.unshift({...event,id:key+':'+now,at:now});this.events=this.events.slice(0,150);if(this.cooldown.size>1000)this.cooldown.delete(this.cooldown.keys().next().value);this.onUpdate?.()}
 observeNetwork(rows){for(const c of rows){if(!c.priceStale&&c.price>0){const key=c.id||c.coin,sourceKey=(c.priceSource||'')+':'+(c.priceCurrency||'USD');const old=this.quotes.get(key);if(old&&old.sourceKey===sourceKey&&Date.now()-old.at<=300000){const change=(c.price/old.price-1)*100;if(Math.abs(change)>=2){this.add({kind:'price',coin:c.coin,title:(change>0?'↑ ':'↓ ')+c.coin+' 短时价格变化 '+change.toFixed(2)+'%',body:'本机观察窗口≤5分钟；'+old.price+' → '+c.price+' '+(c.priceCurrency||'USD')+'。来源 '+c.priceSource,source:c.sourceUrl},'price:'+c.coin+':'+(change>0?'up':'down'));this.quotes.set(key,{price:c.price,at:Date.now(),sourceKey})}}else this.quotes.set(key,{price:c.price,at:Date.now(),sourceKey})}}}
 observeProfits(result){for(const c of result?.coins||[]){if(c.stale||c.net===null)continue;const signature=JSON.stringify((c.rows||[]).map(r=>[r.id,r.measured?'measured':r.manual?'manual':'reference']));const old=this.profits.get(c.coin);if(old&&old.signature===signature&&old.net>0&&c.net>old.net*1.1&&Date.now()-old.at<1800000)this.add({kind:'profit',coin:c.coin,title:c.coin+' 预估净收益上涨 '+((c.net/old.net-1)*100).toFixed(1)+'%',body:'相同设备/电价条件下：$'+old.net.toFixed(2)+' → $'+c.net.toFixed(2)+'/日，属于测算变化，非矿池到账。',source:'https://gozero.trade/'+c.coin.toLowerCase()},'profit:'+c.coin);this.profits.set(c.coin,{net:c.net,at:Date.now(),signature})}}
 resetProfits(){this.profits.clear()}
 async refresh(){if(this.pending)return this.pending;this.pending=(async()=>{try{const d=JSON.parse((await this.request(URL,{maxBytes:12*1024*1024})).toString('utf8'));if(!Array.isArray(d.assets)||d.assets.length>10000)throw Error('行情目录无效');if(d.stale||d.error)throw Error('目录来源过期，暂不生成新提醒');this.observeNetwork(d.assets.map(a=>({id:'market:'+a.id,coin:a.symbol,price:a.price,priceStale:!!a.stale||!Number.isFinite(a.priceTime)||Date.now()-a.priceTime>180000||a.priceTime>Date.now()+60000,priceSource:a.priceSource,priceCurrency:a.priceCurrency,sourceUrl:'https://pro.gozero.trade/'})));const priorCount=Object.keys(this.baseline).length;for(const a of d.assets){if(!a.id||typeof a.symbol!=='string')continue;if(this.initialized&&priorCount&& !this.baseline[a.id])this.add({kind:'new',coin:a.symbol,title:'新收录 PoW：'+a.name+' ('+a.symbol+')',body:'首次出现在本机跟踪目录；算法 '+(a.algorithms||[]).join(' / ')+'。目录新增不等同于项目刚发布。',source:'https://pro.gozero.trade/'},'new:'+a.id);this.baseline[a.id]={symbol:a.symbol,name:a.name};}if(!this.initialized)this.add({kind:'system',coin:'',title:'信息监控已建立基线',body:'已跟踪 '+d.assets.length+' 个 PoW 资产。后续记录新收录、≤5分钟价格变化≥2%、相同配置收益上升≥10%；15分钟去重。',source:'https://pro.gozero.trade/'},'baseline');this.initialized=true;this.at=Date.now();this.error=null;await this.save()}catch(e){this.error=e.message}finally{this.pending=null;this.onUpdate?.()}})();return this.pending}
 save(){const body=JSON.stringify({events:this.events,baseline:this.baseline,initialized:this.initialized});this.queue=(this.queue||Promise.resolve()).catch(()=>{}).then(async()=>{await fs.mkdir(path.dirname(this.file),{recursive:true});await fs.writeFile(this.file+'.tmp',body);await fs.rename(this.file+'.tmp',this.file)});return this.queue}
 snapshot(){return{events:this.events,at:this.at,error:this.error,refreshing:!!this.pending,tracked:Object.keys(this.baseline).length}}
 start(){this.closed=false;const tick=async()=>{if(this.closed)return;await this.refresh();if(!this.closed)this.timer=setTimeout(tick,120000)};this.timer=setTimeout(tick,3500)}
 stop(){this.closed=true;clearTimeout(this.timer);return this.save().catch(()=>{})}
}
module.exports={Intelligence};
