'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const ENDPOINT='https://pro.gozero.trade/api/assistant/benchmarks';
// The deployed receiver currently accepts PRL/QTC only. Keep other algorithm
// records locally so one unsupported record cannot block the upload queue.
const uploadable=row=>['PRL','QTC'].includes(row.record.coin);
function makeRecord(job,session,hw,version){const gpu=(['ZCD','BNT'].includes(session.coin)?[require('./mining-devices.cjs').cpuDevice(hw)].filter(Boolean):hw.gpus).find(g=>g.id===job.id),samples=job.samples.filter(x=>x.at>session.startedAt+15000&&x.at>Date.now()-300000&&Number.isFinite(x.hash)&&x.hash>0);if(!gpu||samples.length<10||samples.at(-1).at-samples[0].at<30000)return null;const values=samples.map(x=>x.hash),powers=job.powers.filter(v=>Number.isFinite(v)&&v>0);return{schema:1,id:crypto.randomUUID(),at:Date.now(),coin:session.coin,algorithm:session.coin==='BNT'?'Argon2id':session.coin==='ZCD'?'RandomX v2':session.coin==='YSR'?'SHA-256d':session.coin==='PRL'?'PearlHash':'Poseidon2',...(['ZCD','BNT'].includes(session.coin)?{deviceKind:'CPU',threads:session.cpuThreads}:{}),model:gpu.name.slice(0,120),vendor:gpu.vendor,memoryMiB:gpu.memoryMiB??null,driver:String(gpu.driver||'').slice(0,60),kernel:session.coin==='BNT'?'Gozero Blocknet CPU':session.coin==='ZCD'?'XMRig':session.coin==='YSR'?'Gozero YSR CUDA':'KRig',kernelVersion:session.coin==='BNT'?require('./bnt-kernel.json').version:session.coin==='ZCD'?'6.26.0':session.coin==='YSR'?require('./ysr-kernel.json').version:'1.5.4',appVersion:version,performance:session.performance||75,duty:job.duty??session.duty??(['ZCD','BNT'].includes(session.coin)?(session.performance||75):Math.round((session.performance||75)*.9)),hash:values.reduce((a,b)=>a+b,0)/values.length,hashMin:Math.min(...values),hashMax:Math.max(...values),unit:'H/s',watts:powers.length?powers.reduce((a,b)=>a+b,0)/powers.length:null,seconds:(samples.at(-1).at-samples[0].at)/1000,samples:samples.length,kind:session.benchmark?'benchmark':'mining',verification:'client-reported'};}
class Records{
 constructor(dir,request,changed){this.file=path.join(dir,'device-records.json');this.request=request;this.changed=changed;this.rows=[];this.last=new Map();this.pending=null;this.error=null;this.enabled=false;this.queue=Promise.resolve()}
 async load(){try{const d=JSON.parse(await fs.readFile(this.file,'utf8'));if(d.schema===1&&Array.isArray(d.rows))this.rows=d.rows.slice(-500)}catch{}}
 async save(){const body=JSON.stringify({schema:1,rows:this.rows});this.queue=this.queue.catch(()=>{}).then(async()=>{await fs.mkdir(path.dirname(this.file),{recursive:true});await fs.writeFile(this.file+'.tmp',body);await fs.rename(this.file+'.tmp',this.file)});return this.queue}
 capture(miner,hw,fee,version){if(!miner.session||fee?.phase==='service'||fee?.switching)return;let added=false;for(const j of miner.jobs.values()){const key=j.id+':'+miner.session.startedAt;if(Date.now()-(this.last.get(key)||0)<300000)continue;const r=makeRecord(j,miner.session,hw,version);if(!r)continue;this.last.set(key,Date.now());this.rows.push({record:r,uploaded:false});added=true;if(this.rows.length>500)this.rows.shift();}if(!added)return;if(this.last.size>100)this.last.delete(this.last.keys().next().value);this.save().catch(e=>{this.error=e.message});this.changed?.();}
 async flush(){if(!this.enabled||this.pending)return;this.pending=(async()=>{try{for(const row of this.rows.filter(r=>!r.uploaded&&uploadable(r)).slice(0,8)){if(!this.enabled)break;const reply=JSON.parse((await this.request(ENDPOINT,{method:'POST',body:JSON.stringify(row.record),maxBytes:64000,timeout:10000})).toString('utf8'));if(reply.accepted!==true)throw Error('服务器未确认记录');row.uploaded=true;await this.save()}this.error=null}catch(e){this.error=e.message}finally{this.pending=null;this.changed?.()}})();return this.pending}
 snapshot(){return{count:this.rows.length,pending:this.rows.filter(r=>!r.uploaded).length,uploaded:this.rows.filter(r=>r.uploaded).length,sharing:this.enabled,error:this.error}}
 export(){return{schema:1,note:'本机实测，自报数据未经矿池证明；不包含钱包、硬件序列号或本机设备标识。',records:this.rows.map(r=>r.record)}}
}
module.exports={Records,makeRecord,ENDPOINT};
